Repository hmcts/div-petitioner-frontend, pull requests merged in 2018-11, with the labels that each got.

#342 Cos master
  Jenkinsfile_CNP
  app/components/AddressLookupStep/template.html
  app/middleware/draftPetitionStoreMiddleware.js
  app/services/healthcheck.js
  config/custom-environment-variables.yaml
  config/default.yaml
  infrastructure/main.tf
  infrastructure/output.tf
  infrastructure/preview.tfvars
  infrastructure/prod.tfvars
  infrastructure/saat.tfvars
  infrastructure/sandbox.tfvars
  infrastructure/sprod.tfvars
  infrastructure/variables.tf
  kubernetes/config.aat.yaml
Labels: ns:div-pfe-pr-342

#338 Changes to use COS instead of CPS
  Jenkinsfile_CNP
  app/components/AddressLookupStep/template.html
  app/middleware/draftPetitionStoreMiddleware.js
  app/services/healthcheck.js
  config/custom-environment-variables.yaml
  config/default.yaml
  infrastructure/main.tf
  infrastructure/output.tf
  infrastructure/preview.tfvars
  infrastructure/saat.tfvars
  infrastructure/sandbox.tfvars
  infrastructure/sprod.tfvars
  infrastructure/variables.tf
  kubernetes/config.aat.yaml
Labels: ns:div-pfe-pr-338

#346 only show respondent consent if feature flag is active
  app/steps/grounds-for-divorce/reason/index.js
  app/steps/grounds-for-divorce/reason/index.test.js
  config/custom-environment-variables.yaml
  config/default.yaml
  infrastructure/aat.tfvars
  infrastructure/main.tf
  infrastructure/variables.tf
  test/end-to-end/paths/reasonsForDivorce.js
Labels: ns:div-pfe-pr-346

#347 Add missing output variable which causing functionality to persist on live still
  infrastructure/output.tf
Labels: ns:div-pfe-pr-347

#351 Fix failing e2e test
  test/end-to-end/codecept.conf.js
  test/end-to-end/pages/pay/by-card-online-on-govpay.js
Labels: ns:div-pfe-pr-351

#352 Fix way boolean is passed for feature flag respondentConsent
  app/steps/grounds-for-divorce/reason/index.js
Labels: ns:div-pfe-pr-352

#340 Redirect to DN if no case or not AwaitingPayment
  app/core/steps/ValidationStep.js
  app/core/steps/ValidationStep.test.js
  app/middleware/redirectMiddleware.js
  app/middleware/redirectMiddleware.test.js
  app/steps/authenticated/index.js
  config/custom-environment-variables.yaml
  config/default.yaml
  infrastructure/aat.tfvars
  infrastructure/demo.tfvars
  infrastructure/main.tf
  infrastructure/preview.tfvars
  infrastructure/prod.tfvars
  infrastructure/saat.tfvars
  infrastructure/sandbox.tfvars
  infrastructure/variables.tf
  kubernetes/config.aat.yaml
  package.json
  yarn.lock
Labels: ns:div-pfe-pr-340

#354 Fix healthchecks
  app/services/healthcheck.js
Labels: ns:div-pfe-pr-354
