Repository hmcts/div-petitioner-frontend, pull requests merged in 2019-08, with the labels that each got.

#584 DIV-5406: Fixing bug from "DIV-4238: PFE - use court information from COS response"
  app/middleware/commonContent.js
  app/middleware/redirectMiddleware.js
  app/middleware/redirectMiddleware.test.js
  app/services/mocks/transformationServiceClient.js
  app/services/submission.js
  app/services/submission.test.js
  app/steps/authenticated/index.test.js
  app/steps/check-your-answers/index.js
  app/steps/check-your-answers/index.test.js
  app/steps/done-and-submitted/content.json
  app/steps/done-and-submitted/index.js
  app/steps/done-and-submitted/index.test.js
  app/steps/done-and-submitted/template.html
  app/steps/pay/pay-online-only/index.js
  app/steps/pay/pay-online-only/index.test.js
  config/custom-environment-variables.yaml
  config/default.yaml
  infrastructure/main.tf
  infrastructure/preview.tfvars
  infrastructure/variables.tf
  test/end-to-end/data/amendPetitionSession.js
  test/examples/courts/serviceCentre.json
  test/fixtures/mockSession.json
Labels: ns:div-pfe-pr-584

#579 DIV-4001 - Upgrade to the latest nodejs version
  .nvmrc
  Dockerfile
  Jenkinsfile_CNP
  Jenkinsfile_parameterized
  app/services/sessionSerializer.test.js
  package.json
  test/util/assertions.js
  yarn.lock
Labels: ns:div-pfe-pr-579

#586 Removed nsp from project - deprecated package
  package.json
  yarn.lock
Labels: ns:div-pfe-pr-586

#585 DIV-2827 - Fix Unhandled Promise Exception
  package.json
  test/end-to-end/helpers/ElementExist.js
  test/end-to-end/helpers/JSWait.js
Labels: ns:div-pfe-pr-585

#587 Use div-pay-client 7.0.0
  package.json
  yarn.lock
Labels: ns:div-pfe-pr-587

#592 DIV-5634 - Update vault definitions for DN, RFE and PFE
  Jenkinsfile_CNP
  package.json
Labels: ns:div-pfe-pr-592

#594 retry request to validate html
  package.json
  test/validation/htmlTest.js
  yarn.lock
Labels: ns:div-pfe-pr-594

#589 update feedback content to be acurate
  app/content/common.json
Labels: ns:div-pfe-pr-589

#588 DIV-4614 - Focus - find address button
  app/components/AddressLookupStep/index.test.js
  app/components/AddressLookupStep/template.html
Labels: ns:div-pfe-pr-588

#591 DIV-4657 - Accessibility [A] - Skipped content in expandable links
  app/assets/javascripts/details.polyfill.js
  webpack.config.js
Labels: ns:div-pfe-pr-591

#590 Accessibility [A] - Error notification focus for screen readers
  app/assets/javascripts/documentUpload.js
  app/components/AddressLookupStep/template.html
  app/steps/check-your-answers/template.html
  app/steps/marriage/upload/template.html
  app/views/question.html
Labels: ns:div-pfe-pr-590

#599 Updated Dockerfile/helm to use hmctspublic
  charts/div-pfe/Chart.yaml
  charts/div-pfe/requirements.yaml
  charts/div-pfe/values.preview.template.yaml
Labels: ns:div-pfe-pr-599

#600 Fix cross browser tests on nightly pipeline
  Jenkinsfile_nightly
  bin/run-crossbrowser-tests.sh
  config/default.yaml
  test/crossbrowser/supportedBrowsers.js
  test/end-to-end/helpers/idamHelper.js
  test/end-to-end/pages/address/postcode.js
  test/end-to-end/pages/check-your-answers/check-your-answers.js
  test/end-to-end/pages/done-and-submitted/done-and-submitted.js
  test/end-to-end/pages/financial/advice.js
  test/end-to-end/pages/financial/arrangements.js
  test/end-to-end/pages/grounds-for-divorce/reason.js
  test/end-to-end/pages/grounds-for-divorce/unreasonable-behaviour.js
  test/end-to-end/pages/help/need-help.js
  test/end-to-end/pages/help/with-fees.js
  test/end-to-end/pages/jurisdiction/habitual-residence.js
  test/end-to-end/pages/jurisdiction/interstitial.js
  test/end-to-end/pages/legal/legal-proceedings.js
  test/end-to-end/pages/living-arrangements/live-together.js
  test/end-to-end/pages/marriage/certificate-names.js
  test/end-to-end/pages/marriage/date.js
  test/end-to-end/pages/marriage/husband-or-wife.js
  test/end-to-end/pages/marriage/married-in-uk.js
  test/end-to-end/pages/marriage/names.js
  test/end-to-end/pages/petitioner/changed-name.js
  test/end-to-end/pages/petitioner/confidential.js
  test/end-to-end/pages/petitioner/contact-details.js
  test/end-to-end/pages/petitioner/use-home-address.js
  test/end-to-end/pages/prayer/claim-costs.js
  test/end-to-end/pages/respondent/use-home-address.js
  test/end-to-end/pages/screening-questions/has-marriage-broken.js
  test/end-to-end/pages/screening-questions/has-marriage-cert.js
  test/end-to-end/pages/screening-questions/has-respondent-address.js
  test/end-to-end/pages/screening-questions/read-financial-remedy.js
  test/end-to-end/saucelabs.conf.js
  zapKnownIssues.xml
Labels: ns:div-pfe-pr-600

#597 DIV-5359 - Accessibility [A] - Page Titles
  app/steps/check-your-answers/template.html
  app/steps/marriage/upload/template.html
  app/views/cookie.html
  app/views/layout.html
  sonar-project.properties
Labels: ns:div-pfe-pr-597

#595 DIV-4617 - Accessibility [A] - Associate data cells with appropriate headers - CYA pages
  app/services/jurisdiction/legalCheckYourAnswersTemplate.html
  app/steps/check-your-answers/content.json
  app/steps/check-your-answers/template.html
  app/steps/financial/arrangements/partials/checkYourAnswersTemplate.html
  app/steps/grounds-for-divorce/adultery/3rd-party/details/partials/checkYourAnswersTemplate.html
  app/steps/grounds-for-divorce/adultery/details/partials/checkYourAnswersTemplate.html
  app/steps/grounds-for-divorce/desertion/when-left/partials/checkYourAnswersTemplate.html
  app/steps/grounds-for-divorce/lived-apart-since/partials/checkYourAnswersTemplate.html
  app/steps/grounds-for-divorce/reason/partials/checkYourAnswersTemplate.html
  app/steps/grounds-for-divorce/separation-date-new/partials/checkYourAnswersTemplate.html
  app/steps/grounds-for-divorce/separation-date/partials/checkYourAnswersTemplate.html
  app/steps/grounds-for-divorce/unreasonable-behaviour/partials/checkYourAnswersTemplate.html
  app/steps/help/need-help/partials/checkYourAnswersTemplate.html
  app/steps/jurisdiction/domicile/partials/checkYourAnswersTemplate.html
  app/steps/jurisdiction/habitual-residence/partials/checkYourAnswersTemplate.html
  app/steps/jurisdiction/last-habitual-residence/partials/checkYourAnswersTemplate.html
  app/steps/legal/legal-proceedings/partials/checkYourAnswersTemplate.html
  app/steps/living-arrangements/live-together/partials/checkYourAnswersTemplate.html
  app/steps/marriage/about-your-marriage-certificate/partials/checkYourAnswersTemplate.html
  app/steps/marriage/certificate-names/partials/checkYourAnswersTemplate.html
  app/steps/marriage/date/partials/checkYourAnswersTemplate.html
  app/steps/marriage/foreign-certificate/partials/checkYourAnswersTemplate.html
  app/steps/marriage/husband-or-wife/partials/checkYourAnswersTemplate.html
  app/steps/marriage/names/partials/checkYourAnswersTemplate.html
  app/steps/marriage/upload/partials/checkYourAnswersTemplate.html
  app/steps/petitioner/changed-name/partials/checkYourAnswersTemplate.html
  app/steps/petitioner/confidential/partials/checkYourAnswersTemplate.html
  app/steps/petitioner/contact-details/partials/checkYourAnswersTemplate.html
  app/steps/prayer/claim-costs/partials/checkYourAnswersTemplate.html
  app/steps/respondent/correspondence/send-to-solicitor/partials/checkYourAnswersTemplate.html
  app/views/common/components/defaultCheckYouAnswersTemplate.html
Labels: ns:div-pfe-pr-595

#593 DIV-5349 - Accessibility [A] - Focus
  app/assets/javascripts/dynamicFields.js
  app/assets/javascripts/dynamicFields.test.js
Labels: ns:div-pfe-pr-593
