Repository hmcts/div-petitioner-frontend, pull requests merged in 2019-09, with the labels that each got.

#609 Remove NOSONAR on HTML
  app/steps/check-your-answers/template.html
Labels: ns:div-pfe-pr-609

#613 Enable strategic pay on Production env
  infrastructure/prod.tfvars
Labels: ns:div-pfe-pr-613

#617 PROD FIX: parse feature as bool so it copes with strings
  app.js
Labels: ns:div-pfe-pr-617

#614 Use hmcts/cnp modules
  infrastructure/main.tf
Labels: ns:div-pfe-pr-614

#608 DIV-5719 - duplicate payment fix
  .gitignore
  README.md
  app.js
  app/services/mocks/payment.js
  app/services/payment.js
  app/services/payment.test.js
  app/steps/pay/awaiting-payment-status/content.json
  app/steps/pay/awaiting-payment-status/index.js
  app/steps/pay/awaiting-payment-status/index.test.js
  app/steps/pay/awaiting-payment-status/template.html
  app/steps/pay/pay-online-only/index.js
  app/steps/pay/pay-online-only/index.test.js
  config/example-local-aat.yml
  package.json
Labels: ns:div-pfe-pr-608

#621 Accessibility statement
  app/steps/accessibility-statement/content.json
  app/steps/accessibility-statement/index.js
  app/steps/accessibility-statement/index.test.js
  app/steps/accessibility-statement/template.html
  app/views/layout.html
Labels: ns:div-pfe-pr-621

#616 redirect to date of marriage page if no date on reason for divorce
  app/middleware/checkMarriageDateMiddleware.js
  app/middleware/checkMarriageDateMiddleware.test.js
  app/steps/grounds-for-divorce/reason/index.js
  app/steps/grounds-for-divorce/reason/index.test.js
Labels: ns:div-pfe-pr-616

#619 use correct node version on aat and prod
  infrastructure/main.tf
  infrastructure/variables.tf
  package.json
  yarn.lock
Labels: ns:div-pfe-pr-619
