Repository hmcts/div-petitioner-frontend, pull requests merged in 2019-01, with the labels that each got.

#361 Added missing IDAM Client-ID required for SIDAM functionality
  infrastructure/main.tf
  infrastructure/variables.tf
  kubernetes/config.aat.yaml
Labels: ns:div-pfe-pr-361

#373 DIV-3830: Changed simulate email address with valid gmail for int tests
  app/middleware/idamProtectMiddleware.test.js
  app/middleware/setIdamDetailsToSessionMiddleware.test.js
  app/services/transformationServiceClient.test.js
  app/steps/pay/card-payment-status/index.test.js
  app/steps/pay/pay-online-only/index.test.js
  app/steps/petitioner/contact-details/index.test.js
  test/end-to-end/helpers/idamHelper.js
Labels: ns:div-pfe-pr-373

#375 DIV-3857 - Improve payment logging
  app/middleware/submissionMiddleware.js
  app/steps/pay/card-payment-status/index.js
  app/steps/pay/card-payment-status/paymentStatusService.js
  app/steps/pay/pay-online-only/index.js
Labels: ns:div-pfe-pr-375

#377 Fix azurerm provider number to 1.19.0
  infrastructure/main.tf
Labels: ns:div-pfe-pr-377

#379 Fixing typos
  app/core/helpers/staleDataManager.js
  app/steps/financial/arrangements/index.js
Labels: ns:div-pfe-pr-379

#376 DIV-2623: Added apply for divorce banner at top of CYA and fixed typo
  README.md
  app/steps/check-your-answers/content.json
  app/steps/check-your-answers/template.html
Labels: ns:div-pfe-pr-376

#381 DIV-3469 - filter out empty values before schema validation
  app/core/fixtures/content/simple.json
  app/core/fixtures/schemas/simple.json
  app/core/steps/ValidationStep.js
  app/core/steps/ValidationStep.test.js
  package.json
  yarn.lock
Labels: ns:div-pfe-pr-381

#384 DIV-3951 - log error message on submission failure
  app/steps/check-your-answers/index.js
Labels: ns:div-pfe-pr-384

#385 DIV-3930 - set DN production URL
  infrastructure/prod.tfvars
Labels: ns:div-pfe-pr-385

#392 Use normal ASP with larger instance size
  infrastructure/main.tf
Labels: ns:div-pfe-pr-392

#393 Brings the prod config court allocation ratios
  infrastructure/prod.tfvars
Labels: ns:div-pfe-pr-393

#397 Enable functional tests
  package.json
Labels: ns:div-pfe-pr-397

#395 Remove instance size
  infrastructure/main.tf
Labels: ns:div-pfe-pr-395

#399 Change CTSC siteId to servicecentre
  infrastructure/variables.tf
Labels: ns:div-pfe-pr-399

#402 DIV-4005 apply empty saveAndClose block to ensure no button show
  app/steps/screening-questions/has-marriage-cert/index.test.js
  app/steps/screening-questions/has-marriage-cert/template.html
  app/steps/screening-questions/has-respondent-address/index.test.js
  app/steps/screening-questions/has-respondent-address/template.html
Labels: ns:div-pfe-pr-402

#369 DIV-3815 Apply style change for Firefox -> CYA page
  app/assets/sass/_check-your-answers.scss
  app/steps/check-your-answers/template.html
Labels: ns:div-pfe-pr-369

#362 5 year separation additional dates
  app/services/separationDates.js
  app/steps/exit/statement-of-case/separation-six-month-period/content.json
  app/steps/exit/statement-of-case/separation-six-month-period/index.js
  app/steps/exit/statement-of-case/separation-six-month-period/index.test.js
  app/steps/exit/statement-of-case/separation-six-month-period/schema.json
  app/steps/exit/statement-of-case/separation-six-month-period/template.html
  app/steps/grounds-for-divorce/lived-apart-since/content.json
  app/steps/grounds-for-divorce/lived-apart-since/index.js
  app/steps/grounds-for-divorce/lived-apart-since/index.test.js
  app/steps/grounds-for-divorce/lived-apart-since/partials/checkYourAnswersTemplate.html
  app/steps/grounds-for-divorce/lived-apart-since/schema.json
  app/steps/grounds-for-divorce/lived-apart-since/template.html
  app/steps/grounds-for-divorce/reason/index.js
  app/steps/grounds-for-divorce/reason/index.test.js
  app/steps/grounds-for-divorce/respondent-consent/index.js
  app/steps/grounds-for-divorce/respondent-consent/index.test.js
  app/steps/grounds-for-divorce/separation-date-new/content.json
  app/steps/grounds-for-divorce/separation-date-new/index.js
  app/steps/grounds-for-divorce/separation-date-new/index.test.js
  app/steps/grounds-for-divorce/separation-date-new/partials/checkYourAnswersTemplate.html
  app/steps/grounds-for-divorce/separation-date-new/schema.json
  app/steps/grounds-for-divorce/separation-date-new/template.html
  app/steps/grounds-for-divorce/separation-date/index.test.js
  config/custom-environment-variables.yaml
  config/default.yaml
  infrastructure/main.tf
  infrastructure/preview.tfvars
  infrastructure/variables.tf
  kubernetes/config.aat.yaml
  test/end-to-end/pages/grounds-for-divorce/lived-apart-since.js
  test/end-to-end/pages/grounds-for-divorce/separation-date-new.js
  test/end-to-end/paths/reasonsForDivorce.js
  test/fixtures/mockSession.json
  test/util/assertions.js
Labels: ns:div-pfe-pr-362

#403 Content update for progress bar
  app/steps/done-and-submitted/content.json
Labels: ns:div-pfe-pr-403

#406 Add missing feature_release 510 to the env outputs
  infrastructure/output.tf
Labels: ns:div-pfe-pr-406

#409 Attempt to fix failing E2E tests
  kubernetes/config.aat.yaml
  test/end-to-end/pages/grounds-for-divorce/separation-date-new.js
  test/end-to-end/paths/reasonsForDivorce.js
  test/end-to-end/paths/save-resume.js
Labels: ns:div-pfe-pr-409

#414 parseBool all featureToggles
  app/core/steps/DestroySessionStep.js
  app/core/steps/DestroySessionStep.test.js
  app/middleware/idamProtectMiddleware.js
  app/services/submission.js
  app/steps/authenticated/index.js
  app/steps/check-your-answers/index.js
  app/steps/pay/card-payment-status/paymentStatusService.js
  app/steps/pay/pay-online-only/index.js
  app/steps/start/index.js
  test/end-to-end/helpers/idamHelper.js
  test/end-to-end/pages/index/index.js
  test/end-to-end/pages/petitioner/contact-details.js
  test/end-to-end/paths/logout.js
  test/end-to-end/paths/reasonsForDivorce.js
  test/end-to-end/paths/save-resume.js
  test/mocks/idam.js
Labels: ns:div-pfe-pr-414

#413 Changed serviceCentre court email. This only affects the done pages
  infrastructure/variables.tf
  kubernetes/config.aat.yaml
Labels: ns:div-pfe-pr-413

#329 Confidential and contact content update
  app/steps/petitioner/confidential/content.json
  app/steps/petitioner/confidential/template.html
  app/steps/petitioner/contact-details/content.json
  app/steps/petitioner/contact-details/index.test.js
  app/steps/petitioner/contact-details/template.html
Labels: ns:div-pfe-pr-329

#408 DIV-4036 improve logging
  app.js
  app/core/initSteps.js
  app/core/steps/Step.js
  app/middleware/commonContent.js
  app/middleware/draftPetitionStoreMiddleware.js
  app/middleware/evidenceManagmentMiddleware.js
  app/middleware/sessions.js
  app/middleware/submissionMiddleware.js
  app/middleware/updateApplicationFeeMiddleware.js
  app/services/evidenceManagmentService.js
  app/services/fileManagement.js
  app/services/healthcheck.js
  app/services/logger.js
  app/services/logger.test.js
  app/services/payment.js
  app/services/rateLimiter.js
  app/services/serviceToken.js
  app/services/sessionSerializer.js
  app/services/submission.js
  app/steps/check-your-answers/index.js
  app/steps/grounds-for-divorce/reason/index.js
  app/steps/pay/card-payment-status/index.js
  app/steps/pay/card-payment-status/paymentStatusService.js
  app/steps/pay/gov-pay-stub/index.js
  app/steps/pay/pay-online-only/index.js
  package.json
  server.js
  test/end-to-end/codecept.conf.js
  test/end-to-end/helpers/SessionHelper.js
  test/end-to-end/helpers/idamHelper.js
  test/end-to-end/paths/basicDivorce.js
  yarn.lock
Labels: ns:div-pfe-pr-408
