Repository hmcts/div-petitioner-frontend, pull requests merged in 2019-05, with the labels that each got.

#530 Enable serviceCallbackUrl again
  app/services/payment.js
  app/services/payment.test.js
Labels: ns:div-pfe-pr-530

#523 Capture Solicitor Email and Phone Number optionally
  app/steps/respondent/correspondence/send-to-solicitor/content.json
  app/steps/respondent/correspondence/use-home-address/content.json
  app/steps/respondent/solicitor/details/content.json
  app/steps/respondent/solicitor/details/index.js
  app/steps/respondent/solicitor/details/index.test.js
  app/steps/respondent/solicitor/details/schema.json
  app/steps/respondent/solicitor/details/template.html
Labels: ns:div-pfe-pr-523

#531 Change layout for Addresses on CYA
  app/steps/living-arrangements/last-lived-together/at-petitioner-home-address/partials/checkYourAnswersTemplate.html
  app/steps/petitioner/correspondence/use-home-address/partials/checkYourAnswersTemplate.html
  app/steps/respondent/correspondence/use-home-address/partials/checkYourAnswersTemplate.html
  app/steps/respondent/home/lives-at-last-address/partials/checkYourAnswersTemplate.html
Labels: ns:div-pfe-pr-531

#533 security scan fix
  security.sh
  zapKnownIssues.xml
Labels: ns:div-pfe-pr-533

#535 Feature Toggle Strategic Callback
  app/steps/pay/pay-online-only/index.js
  app/steps/pay/pay-online-only/index.test.js
  charts/div-pfe/values.aat.template.yaml
  charts/div-pfe/values.preview.template.yaml
  config/custom-environment-variables.yaml
  config/default.yaml
  infrastructure/aat.tfvars
  infrastructure/demo.tfvars
  infrastructure/main.tf
  infrastructure/preview.tfvars
  infrastructure/saat.tfvars
  infrastructure/variables.tf
Labels: ns:div-pfe-pr-535

#536 Statement of truth field should never be checked
  app/steps/check-your-answers/index.js
  app/steps/check-your-answers/index.test.js
Labels: ns:div-pfe-pr-536

#515 Point to SIDAM
  Jenkinsfile_CNP
  infrastructure/aat.tfvars
  infrastructure/demo.tfvars
  infrastructure/sandbox.tfvars
  infrastructure/sprod.tfvars
Labels: ns:div-pfe-pr-515

#541 DIV-3532 fix missing divorce options
  Dockerfile
  Gruntfile.js
  Makefile
  README.md
  app/core/utils/baseUrl.js
  app/core/utils/baseUrl.test.js
  app/middleware/draftPetitionStoreMiddleware.js
  app/middleware/draftPetitionStoreMiddleware.test.js
  charts/div-pfe/values.yaml
  config/default.yaml
  docker/dev-compose.yaml
  docker/jenkins-compose.yaml
  package.json
  sonar-project.properties
  test/end-to-end/helpers/SessionHelper.js
Labels: ns:div-pfe-pr-541

#542 DIV-4860 - removed unnecessary sandbox stubbing
  app/middleware/draftPetitionStoreMiddleware.test.js
Labels: ns:div-pfe-pr-542

#544 Update feeToBePaid if it is not available in session
  app/steps/pay/pay-online-only/index.js
  app/steps/pay/pay-online-only/index.test.js
Labels: ns:div-pfe-pr-544

#538 DIV-4860 - update the divorce contact email to contactdivorce@...
  bin/run-functional-tests.sh
  charts/div-pfe/values.yaml
  infrastructure/variables.tf
  test/end-to-end/data/amendPetitionSession.js
Labels: ns:div-pfe-pr-538
