Repository hmcts/div-petitioner-frontend, pull requests merged in 2019-04, with the labels that each got.

#502 Disable prod deployments
  Jenkinsfile_CNP
Labels: ns:div-pfe-pr-502

#497 DIV-4583 - fix incorrect step skipping on amend petition
  Gruntfile.js
  app/core/helpers/steps.js
  app/core/helpers/steps.test.js
  app/core/steps/Step.js
  app/core/steps/Step.test.js
  app/steps/check-your-answers/index.js
  app/steps/check-your-answers/index.test.js
  package.json
  test/end-to-end/data/amendPetitionSessionWithConfirmation.js
  test/end-to-end/helpers/SessionHelper.js
  test/end-to-end/pages/index/index.js
  test/end-to-end/paths/amend.js
  test/end-to-end/paths/payment.js
  test/end-to-end/paths/save-resume.js
Labels: ns:div-pfe-pr-497

#466 DIV-4386: Adding text to privacy policy page
  app/steps/privacy-policy/content.json
  app/steps/privacy-policy/template.html
Labels: ns:div-pfe-pr-466

#491 Phase one for tracking non javascript users
  app.js
  app/views/layout.html
Labels: ns:div-pfe-pr-491

#500 fix error where session is being destroyed
  app/steps/authenticated/index.js
  app/steps/authenticated/index.test.js
Labels: ns:div-pfe-pr-500

#485 Correct errors for marriage date page
  app/steps/marriage/date/index.js
  app/steps/marriage/date/index.test.js
Labels: ns:div-pfe-pr-485

#495 DIV-4569: Replaced 530 feature toggle
  Jenkinsfile_CNP
  app/steps/grounds-for-divorce/reason/index.js
  app/steps/grounds-for-divorce/reason/index.test.js
  config/custom-environment-variables.yaml
  config/default.yaml
  infrastructure/main.tf
  infrastructure/output.tf
  infrastructure/preview.tfvars
  infrastructure/variables.tf
  package.json
  test/end-to-end/paths/reasonsForDivorce.js
  yarn.lock
Labels: 5.3.0, ns:div-pfe-pr-495

#509 Update SiteID to A007 for CTSC
  infrastructure/variables.tf
Labels: ns:div-pfe-pr-509

#511 DIV-4669 Enable release520
  config/default.yaml
  config/preview.yaml
  config/testing.yaml
  infrastructure/variables.tf
Labels: ns:div-pfe-pr-511

#481 DIV-3773 Added chart config
  Jenkinsfile_CNP
  app.js
  app/core/setup/setupSecrets.js
  app/core/setup/setupSecrets.test.js
  app/services/healthcheck.js
  charts/div-pfe/Chart.yaml
  charts/div-pfe/requirements.yaml
  charts/div-pfe/values.aat.template.yaml
  charts/div-pfe/values.preview.template.yaml
  charts/div-pfe/values.yaml
  kubernetes/config.aat.yaml
  kubernetes/deployment.template.yaml
  package.json
  server.js
  test/accessibility/a11yTest.js
  yarn.lock
Labels: ns:div-pfe-pr-481

#492 Div 3205 capitalise names before ccd
  app/core/utils/capitalizeName.js
  app/core/utils/capitalizeName.test.js
  app/steps/grounds-for-divorce/adultery/3rd-party/details/index.js
  app/steps/marriage/names/index.js
  app/steps/marriage/names/index.test.js
Labels: ns:div-pfe-pr-492

#517 Remove default postMiddleware in delete draft scenario
  app/steps/save-resume/confirm-remove-saved-application/index.js
  app/steps/save-resume/confirm-remove-saved-application/index.test.js
Labels: ns:div-pfe-pr-517

#516 Postcode lookup API and address formatting update
  Jenkinsfile_CNP
  app/components/AddressLookupStep/addressTypes/postcode.js
  app/components/AddressLookupStep/addressTypes/postcode.test.js
  app/components/AddressLookupStep/helpers/addressHelpers.js
  app/components/AddressLookupStep/mocks/responses/n42sw.json
  app/components/AddressLookupStep/mocks/responses/sw99pe.json
  app/components/AddressLookupStep/template.html
  app/core/setup/setupSecrets.js
  app/core/setup/setupSecrets.test.js
  app/services/postcodeInfo.js
  app/services/postcodeInfo.test.js
  app/steps/check-your-answers/index.test.js
  app/steps/petitioner/correspondence/use-home-address/index.test.js
  charts/div-pfe/values.yaml
  infrastructure/aat.tfvars
  infrastructure/demo.tfvars
  infrastructure/main.tf
  infrastructure/preview.tfvars
  infrastructure/prod.tfvars
  infrastructure/saat.tfvars
  infrastructure/sandbox.tfvars
  infrastructure/sprod.tfvars
  infrastructure/variables.tf
  test/end-to-end/data/amendPetitionSession.js
  test/end-to-end/data/basicDivorceSessionData.js
  test/end-to-end/paths/livingTogether.js
  test/fixtures/mockSession.json
Labels: ns:div-pfe-pr-516

#522 Update sonar-scanner module version
  .gitignore
  package.json
  yarn.lock
Labels: ns:div-pfe-pr-522

#519 Remove all release Feature Flags
  app/steps/grounds-for-divorce/adultery/details/index.js
  app/steps/grounds-for-divorce/adultery/details/index.test.js
  app/steps/grounds-for-divorce/desertion/when-left/index.js
  app/steps/grounds-for-divorce/desertion/when-left/index.test.js
  app/steps/grounds-for-divorce/lived-apart-since/index.js
  app/steps/grounds-for-divorce/reason/index.js
  app/steps/grounds-for-divorce/reason/index.test.js
  app/steps/grounds-for-divorce/separation-date-new/index.js
  app/steps/help/need-help/index.test.js
  charts/div-pfe/values.aat.template.yaml
  charts/div-pfe/values.preview.template.yaml
  config/custom-environment-variables.yaml
  config/default.yaml
  config/development.yaml
  config/example-local-testing.yaml
  config/testing.yaml
  infrastructure/main.tf
  infrastructure/output.tf
  infrastructure/preview.tfvars
  infrastructure/variables.tf
  test/end-to-end/pages/grounds-for-divorce/adultery-details.js
  test/end-to-end/paths/reasonsForDivorce.js
Labels: ns:div-pfe-pr-519

#524 Ignore session validation on sauce lab cross browser
  bin/run-crossbrowser-tests.sh
  config/custom-environment-variables.yaml
  config/default.yaml
  test/crossbrowser/supportedBrowsers.js
  test/end-to-end/paths/basicDivorce.js
Labels: ns:div-pfe-pr-524

#508 DIV-4649: Changing the way we check whether the client's browser accepts cookies
  app/middleware/checkCookiesAllowed.js
  app/middleware/checkCookiesAllowed.test.js
  test/end-to-end/paths/errorPaths.js
Labels: ns:div-pfe-pr-508

#525 fix failed tests on Edge and Safari in Saucelabs
  bin/run-crossbrowser-tests.sh
  config/custom-environment-variables.yaml
  config/default.yaml
  test/crossbrowser/supportedBrowsers.js
  test/end-to-end/pages/marriage/upload.js
  test/end-to-end/paths/basicDivorce.js
  test/end-to-end/saucelabs.conf.js
Labels: ns:div-pfe-pr-525

#521 Enable strategic payment solution
  app/services/payment.js
Labels: ns:div-pfe-pr-521

#526 Use hardcoded day value so differing month days don't throw an error
  app/steps/marriage/date/index.test.js
Labels: ns:div-pfe-pr-526
