Repository hmcts/div-petitioner-frontend, pull requests merged in 2019-06, with the labels that each got.

#545 DIV-4619: added <legend/> tags to <fieldset/>
  app/steps/grounds-for-divorce/adultery/second-hand-information/template.html
  app/steps/legal/legal-proceedings/template.html
Labels: ns:div-pfe-pr-545

#555 Set instance size to I3
  infrastructure/main.tf
Labels: ns:div-pfe-pr-555

#554 DIV-3999: Consolidate naming of responses in health check
  app/services/healthcheck.js
Labels: ns:div-pfe-pr-554

#553 Mapping respondentCorrespondenceSendToSolicitor to respondentSolicitorRepresented
  app/steps/respondent/correspondence/send-to-solicitor/content.json
  app/steps/respondent/correspondence/send-to-solicitor/index.js
  app/steps/respondent/correspondence/send-to-solicitor/index.test.js
  app/steps/respondent/correspondence/send-to-solicitor/partials/checkYourAnswersTemplate.html
  app/steps/respondent/correspondence/send-to-solicitor/schema.json
  app/steps/respondent/correspondence/send-to-solicitor/template.html
  app/steps/respondent/correspondence/use-home-address/index.js
  app/steps/respondent/correspondence/use-home-address/index.test.js
  app/steps/respondent/solicitor/details/index.js
  test/fixtures/mockSession.json
Labels: ns:div-pfe-pr-553

#546 labels update to facilitate understanding on voiceover
  app/assets/sass/application.scss
  app/steps/financial/arrangements/template.html
  app/steps/legal/legal-proceedings/template.html
Labels: ns:div-pfe-pr-546

#550 DIV-4622 screen reader reads case reference ID as seperate characters
  app/components/AddressLookupStep/helpers/addressHelpers.js
  app/filters/nunjucks.js
  app/filters/nunjucks.test.js
  app/services/mocks/transformationServiceClient.js
  app/steps/done-and-submitted/template.html
  app/views/includes/phase_banner.html
Labels: ns:div-pfe-pr-550

#547 Added accessibility for progress bar
  app/steps/done-and-submitted/content.json
  app/steps/done-and-submitted/template.html
Labels: ns:div-pfe-pr-547
