Repository hmcts/div-petitioner-frontend, pull requests merged in 2019-10, with the labels that each got.

#601 DIV-4587 - Accessibility [AA]: Ambiguous links
  app/steps/done-and-submitted/content.json
  app/steps/marriage/upload/content.json
  app/steps/screening-questions/has-marriage-cert/content.json
Labels: ns:div-pfe-pr-601

#623 Webchats - add live environment variables
  infrastructure/prod.tfvars
Labels: ns:div-pfe-pr-623

#626 DIV-5608: Updated Smart survey links to new urls
  infrastructure/variables.tf
Labels: ns:div-pfe-pr-626

#624 Prepare for AKS migration
  Jenkinsfile_CNP
  app.js
  app/core/setup/setupSecrets.js
  app/services/healthcheck.js
  charts/div-pfe/Chart.yaml
  charts/div-pfe/requirements.yaml
  charts/div-pfe/values.aat.template.yaml
  charts/div-pfe/values.preview.template.yaml
  charts/div-pfe/values.yaml
  config/production.yml
  infrastructure/main.tf
  infrastructure/variables.tf
Labels: ns:div-pfe-pr-624

#628 Fix spelling
  infrastructure/main.tf
Labels: ns:div-pfe-pr-628

#629 Fixup chart and upgrade appinsights
  .editorconfig
  app/core/setup/setupSecrets.js
  charts/div-pfe/Chart.yaml
  charts/div-pfe/requirements.yaml
  charts/div-pfe/values.preview.template.yaml
  charts/div-pfe/values.yaml
  package.json
  server.js
  yarn.lock
Labels: ns:div-pfe-pr-629

#627 DIV-5756 - Enable webchat on live environment
  charts/div-pfe/values.preview.template.yaml
  config/default.yaml
  infrastructure/variables.tf
Labels: ns:div-pfe-pr-627

#622 DIV-5761 Add test and extra checks for invalid API data
  app/components/AddressLookupStep/addressTypes/postcode.js
  app/components/AddressLookupStep/addressTypes/postcode.test.js
  app/components/AddressLookupStep/index.js
  app/components/AddressLookupStep/mocks/postcodeInfo.js
Labels: ns:div-pfe-pr-622

#634 Change base image to alpine
  Dockerfile
  docker-compose.yml
  infrastructure/.gitignore
  package.json
  yarn.lock
Labels: ns:div-pfe-pr-634

#625 DIV-5764 - Reject and amend - check your answers page
  app/steps/check-your-answers/content.json
  app/steps/check-your-answers/index.test.js
  app/steps/check-your-answers/template.html
Labels: ns:div-pfe-pr-625

#630 DIV-5820 - Right-hand column to show on PFE done page
  app/assets/sass/application.scss
  app/steps/done-and-submitted/content.json
  app/steps/done-and-submitted/index.test.js
  app/steps/done-and-submitted/template.html
  package.json
  sonar-project.properties
Labels: ns:div-pfe-pr-630

#637 Fix code cov for AddressLookupStep
  app/components/AddressLookupStep/index.js
  app/components/AddressLookupStep/index.test.js
  package.json
  sonar-project.properties
Labels: ns:div-pfe-pr-637

#631 DIV-5223 - Response Submitted (after amendment) page
  app/steps/done-and-submitted/content.json
  app/steps/done-and-submitted/index.test.js
  app/steps/done-and-submitted/template.html
Labels: ns:div-pfe-pr-631

#638 Update values.yaml: use proper image (PFE not RFE)
  charts/div-pfe/values.yaml
Labels: ns:div-pfe-pr-638
