Repository hmcts/div-petitioner-frontend, pull requests merged in 2019-07, with the labels that each got.

#563 DIV-5103 - Update email address for divorce cases
  charts/div-pfe/values.yaml
  infrastructure/variables.tf
  test/end-to-end/data/amendPetitionSession.js
Labels: ns:div-pfe-pr-563

#564 DIV-4981 Update CTSC address
  charts/div-pfe/values.yaml
  config/default.yaml
  infrastructure/variables.tf
  test/end-to-end/data/amendPetitionSession.js
Labels: ns:div-pfe-pr-564

#558 DIV-3264 update Readme
  README.md
Labels: ns:div-pfe-pr-558

#567 Fix: package.json upgrade
  package.json
  yarn.lock
Labels: ns:div-pfe-pr-567

#568 DIV-2637: clean up - remove porttactical var
  app.js
  config/custom-environment-variables.yaml
Labels: ns:div-pfe-pr-568

#572 Update to use the public HMCTS docker registry
  Dockerfile
Labels: ns:div-pfe-pr-572

#574 lodash update to 4.17.14
  yarn.lock
Labels: ns:div-pfe-pr-574

#573 DIV-4238: PFE - use court information from COS response
  app/middleware/commonContent.js
  app/middleware/redirectMiddleware.js
  app/middleware/redirectMiddleware.test.js
  app/services/mocks/transformationServiceClient.js
  app/services/submission.js
  app/services/submission.test.js
  app/steps/authenticated/index.test.js
  app/steps/check-your-answers/index.js
  app/steps/check-your-answers/index.test.js
  app/steps/done-and-submitted/content.json
  app/steps/done-and-submitted/index.js
  app/steps/done-and-submitted/index.test.js
  app/steps/done-and-submitted/template.html
  app/steps/pay/pay-online-only/index.js
  app/steps/pay/pay-online-only/index.test.js
  config/custom-environment-variables.yaml
  config/default.yaml
  infrastructure/main.tf
  infrastructure/preview.tfvars
  infrastructure/variables.tf
  test/end-to-end/data/amendPetitionSession.js
  test/examples/courts/serviceCentre.json
  test/fixtures/mockSession.json
Labels: ns:div-pfe-pr-573

#575 Revert "DIV-4238: PFE - use court information from COS response"
  app/middleware/commonContent.js
  app/middleware/redirectMiddleware.js
  app/middleware/redirectMiddleware.test.js
  app/services/mocks/transformationServiceClient.js
  app/services/submission.js
  app/services/submission.test.js
  app/steps/authenticated/index.test.js
  app/steps/check-your-answers/index.js
  app/steps/check-your-answers/index.test.js
  app/steps/done-and-submitted/content.json
  app/steps/done-and-submitted/index.js
  app/steps/done-and-submitted/index.test.js
  app/steps/done-and-submitted/template.html
  app/steps/pay/pay-online-only/index.js
  app/steps/pay/pay-online-only/index.test.js
  config/custom-environment-variables.yaml
  config/default.yaml
  infrastructure/main.tf
  infrastructure/preview.tfvars
  infrastructure/variables.tf
  test/end-to-end/data/amendPetitionSession.js
  test/examples/courts/serviceCentre.json
  test/fixtures/mockSession.json
Labels: ns:div-pfe-pr-575

#576 Upgraded nyc packes to 14.1.1
  package.json
  yarn.lock
Labels: ns:div-pfe-pr-576

#578 Change generator functions in Codecept to Async Await
  test/end-to-end/paths/invalidCsrf.js
  test/end-to-end/paths/payment.js
  test/end-to-end/paths/uploadMarriageCertificate.js
Labels: ns:div-pfe-pr-578

#577 Cross-Browser - Mobile - No Padding on postcode lookup
  app/assets/sass/application.scss
Labels: ns:div-pfe-pr-577

#581 changeEmailNotificationDomain
  test/end-to-end/helpers/idamHelper.js
Labels: ns:div-pfe-pr-581

#580 Adjustments to Code to resolve unit test errors
  app.js
  app/steps/grounds-for-divorce/adultery/details/index.test.js
  app/steps/grounds-for-divorce/lived-apart-since/index.test.js
  app/steps/jurisdiction/residual/index.test.js
  app/steps/marriage/in-the-uk/index.test.js
  package.json
  test/util/assertions.js
  yarn.lock
Labels: ns:div-pfe-pr-580
