Repository hmcts/div-petitioner-frontend, pull requests merged in 2019-02, with the labels that each got.

#426 Remove separation date line from cya with new separation dates
  app/steps/grounds-for-divorce/lived-apart-since/index.test.js
  app/steps/grounds-for-divorce/separation-date-new/content.json
  app/steps/grounds-for-divorce/separation-date-new/partials/checkYourAnswersTemplate.html
  kubernetes/config.aat.yaml
Labels: ns:div-pfe-pr-426

#420 DIV-4036 - add missing req parameter to logger statements
  app/middleware/evidenceManagmentMiddleware.js
  app/middleware/updateApplicationFeeMiddleware.js
  app/services/evidenceManagmentService.js
  app/services/evidenceManagmentService.test.js
  app/services/fileManagement.js
  app/services/fileManagement.test.js
  app/services/payment.js
  app/services/serviceToken.js
  app/services/sessionSerializer.js
  app/services/sessionSerializer.test.js
  app/services/submission.js
  app/steps/check-your-answers/index.js
  app/steps/check-your-answers/index.test.js
  app/steps/pay/card-payment-status/index.test.js
  app/steps/pay/card-payment-status/paymentStatusService.js
  app/steps/pay/pay-online-only/index.js
  app/steps/pay/pay-online-only/index.test.js
Labels: ns:div-pfe-pr-420

#429 set up divorce app security scan
  Jenkinsfile_nightly
  test/security.sh
Labels: ns:div-pfe-pr-429

#427 Div 4146 - PFE: Text change on 5 years separation calculation
  app/services/separationDates.js
  app/steps/grounds-for-divorce/lived-apart-since/content.json
  app/steps/grounds-for-divorce/lived-apart-since/index.test.js
  app/steps/grounds-for-divorce/lived-apart-since/partials/checkYourAnswersTemplate.html
  app/steps/grounds-for-divorce/lived-apart-since/template.html
Labels: ns:div-pfe-pr-427

#431 set up divorce app security scan
  security.sh
Labels: ns:div-pfe-pr-431

#436 Fix payment update code
  app/steps/pay/card-payment-status/paymentStatusService.js
  app/steps/pay/pay-online-only/index.js
  test/end-to-end/pages/address/postcode.js
Labels: ns:div-pfe-pr-436

#433 Fixed getSeparationTimeTogetherPermitted text for more than 6 month s…
  app/services/separationDates.js
  app/services/separationDates.test.js
  package.json
  yarn.lock
Labels: ns:div-pfe-pr-433

#430 Release 5.10
  infrastructure/prod.tfvars
  infrastructure/variables.tf
Labels: ns:div-pfe-pr-430

#412 DIV-4104: Making preparatory change...
  app/steps/check-your-answers/index.js
  app/steps/check-your-answers/index.test.js
  app/steps/prayer/claim-costs/index.test.js
Labels: ns:div-pfe-pr-412

#418 Add serviceCallbackUrl to payment creation
  app/services/payment.js
  app/steps/pay/pay-online-only/index.js
  app/steps/pay/pay-online-only/index.test.js
  package.json
  yarn.lock
Labels: ns:div-pfe-pr-418

#441 Do NOT Merge: Test PR Pointing to COS PR 146
  kubernetes/config.aat.yaml
Labels: ns:div-pfe-pr-441

#442 Revert "Do NOT Merge: Test PR Pointing to COS PR 146"
  kubernetes/config.aat.yaml
Labels: ns:div-pfe-pr-442

#439 DIV-4149: Cleaning up PFE after moving court allocation to COS
  app/services/courtsAllocation.js
  app/services/courtsAllocation.test.js
  app/steps/check-your-answers/index.js
  app/steps/check-your-answers/index.test.js
  config/custom-environment-variables.yaml
  config/default.yaml
  infrastructure/aat.tfvars
  infrastructure/main.tf
  infrastructure/preview.tfvars
  infrastructure/prod.tfvars
  infrastructure/variables.tf
  kubernetes/config.aat.yaml
  package.json
  yarn.lock
Labels: ns:div-pfe-pr-439

#421 Cannot resume after answering no on screening questions
  app.js
  app/assets/sass/application.scss
  app/content/common.json
  app/core/steps/DestroySessionStep.js
  app/core/steps/ScreeningValidationStep.js
  app/core/steps/ScreeningValidationStep.test.js
  app/core/steps/Step.js
  app/routes/sign-out.js
  app/routes/sign-out.test.js
  app/steps/check-your-answers/index.js
  app/steps/check-your-answers/index.test.js
  app/steps/exit/screening-questions/has-marriage-broken/index.js
  app/steps/exit/screening-questions/has-marriage-cert/index.js
  app/steps/exit/screening-questions/has-respondent-address/index.js
  app/steps/screening-questions/has-marriage-broken/index.js
  app/steps/screening-questions/has-marriage-cert/index.js
  app/steps/screening-questions/has-respondent-address/index.js
  app/views/includes/propositional_navigation.html
  test/end-to-end/pages/index/index.js
  test/end-to-end/pages/screening-questions/has-marriage-cert.js
  test/end-to-end/paths/exitPaths.js
  test/end-to-end/paths/logout.js
Labels: ns:div-pfe-pr-421

#443 Fixed Draft Store Tests now that Screening questions do not save draft
  test/end-to-end/paths/save-resume.js
Labels: ns:div-pfe-pr-443

#398 DIV-3964 Adultery details - Info from another person
  app/steps/grounds-for-divorce/adultery/details/index.js
  app/steps/grounds-for-divorce/adultery/details/index.test.js
  app/steps/grounds-for-divorce/adultery/second-hand-information/content.json
  app/steps/grounds-for-divorce/adultery/second-hand-information/index.js
  app/steps/grounds-for-divorce/adultery/second-hand-information/index.test.js
  app/steps/grounds-for-divorce/adultery/second-hand-information/partials/checkYourAnswersTemplate.html
  app/steps/grounds-for-divorce/adultery/second-hand-information/schema.json
  app/steps/grounds-for-divorce/adultery/second-hand-information/template.html
  config/custom-environment-variables.yaml
  config/default.yaml
  infrastructure/main.tf
  infrastructure/output.tf
  infrastructure/preview.tfvars
  infrastructure/variables.tf
  kubernetes/config.aat.yaml
  test/end-to-end/pages/grounds-for-divorce/adultery-details.js
  test/end-to-end/pages/grounds-for-divorce/adultery-second-hand-info.js
  test/end-to-end/paths/reasonsForDivorce.js
  test/fixtures/mockSession.json
Labels: ns:div-pfe-pr-398

#446 Div 3964 putting test behind feature toggle
  app/steps/grounds-for-divorce/adultery/details/index.test.js
  test/end-to-end/pages/grounds-for-divorce/adultery-details.js
Labels: ns:div-pfe-pr-446

#356 Content update to reason screen
  app/steps/grounds-for-divorce/reason/content.json
  app/steps/marriage/date/content.json
Labels: ns:div-pfe-pr-356

#440 Removed the inbuilt HTTP status code util and used a popular npm modu…
  app.js
  app/core/utils/statusCode.js
  app/middleware/draftPetitionStoreMiddleware.js
  app/services/postcodeInfo.js
  app/steps/sitemap/index.test.js
Labels: ns:div-pfe-pr-440

#447 Remove legacy error alert
  infrastructure/error_service.tf
  infrastructure/error_service_action_group.tf
Labels: ns:div-pfe-pr-447

#438 Use sendEmail boolean instead of exposed notificationEmail param
  app/services/transformationServiceClient.js
  app/services/transformationServiceClient.test.js
Labels: ns:div-pfe-pr-438

#428 Activate ACR build, image multistaging and hmcts runtime user
  .dockerignore
  .eslintignore
  Dockerfile
  acb.tpl.yaml
  kubernetes/deployment.template.yaml
  package.json
Labels: docker-optimisation, ns:div-pfe-pr-428

#404 DIV 3981 desertion lived apart
  app/services/separationDates.js
  app/steps/grounds-for-divorce/desertion/agree/index.js
  app/steps/grounds-for-divorce/desertion/agree/index.test.js
  app/steps/grounds-for-divorce/desertion/when-left/index.js
  app/steps/grounds-for-divorce/desertion/when-left/index.test.js
  app/steps/grounds-for-divorce/lived-apart-since/content.json
  app/steps/grounds-for-divorce/lived-apart-since/index.js
  app/steps/grounds-for-divorce/lived-apart-since/index.test.js
  app/steps/grounds-for-divorce/lived-apart-since/partials/checkYourAnswersTemplate.html
  app/steps/grounds-for-divorce/lived-apart-since/template.html
  app/steps/grounds-for-divorce/reason/index.js
  app/steps/grounds-for-divorce/reason/index.test.js
  app/steps/screening-questions/has-respondent-address/template.html
  infrastructure/output.tf
  infrastructure/preview.tfvars
Labels: ns:div-pfe-pr-404

#452 PFE Desertion functional test failure
  test/end-to-end/paths/reasonsForDivorce.js
Labels: ns:div-pfe-pr-452

#453 PFE functional test failure
  test/end-to-end/paths/reasonsForDivorce.js
Labels: ns:div-pfe-pr-453

#386 Amend petition changes - Nav to next unanswered question, fee update, exclude reason for divorce
  app/core/helpers/steps.js
  app/core/helpers/steps.test.js
  app/core/initSteps.js
  app/core/steps/ValidationStep.js
  app/core/steps/ValidationStep.test.js
  app/middleware/draftPetitionStoreMiddleware.js
  app/middleware/draftPetitionStoreMiddleware.test.js
  app/middleware/updateApplicationFeeMiddleware.js
  app/middleware/updateApplicationFeeMiddleware.test.js
  app/services/feesAndPaymentsService.js
  app/services/feesAndPaymentsService.test.js
  app/services/jurisdiction/legalCheckYourAnswersTemplate.html
  app/services/mocks/feesAndPaymentsService.js
  app/steps/authenticated/index.js
  app/steps/check-your-answers/index.js
  app/steps/check-your-answers/index.test.js
  app/steps/grounds-for-divorce/reason/index.js
  app/steps/grounds-for-divorce/reason/index.test.js
  app/steps/help/need-help/content.json
  app/steps/help/need-help/index.js
  app/steps/help/need-help/index.test.js
  app/steps/help/need-help/partials/checkYourAnswersTemplate.html
  app/steps/pay/pay-online-only/content.json
  app/steps/pay/pay-online-only/index.js
  app/steps/pay/pay-online-only/index.test.js
  app/steps/petitioner/contact-details/index.js
  app/steps/petitioner/contact-details/schema.json
  config/default.yaml
  test/end-to-end/helpers/SessionHelper.js
  test/end-to-end/paths/save-resume.js
Labels: ns:div-pfe-pr-386

#454 DIV-4288 Allow for delete application path navigation when Amend Petition
  app/core/steps/ValidationStep.js
  app/core/steps/ValidationStep.test.js
  app/middleware/draftPetitionStoreMiddleware.js
  app/steps/save-resume/confirm-remove-saved-application/index.js
  sonar-project.properties
  test/end-to-end/data/amendPetitionSession.js
  test/end-to-end/helpers/SessionHelper.js
  test/end-to-end/pages/index/index.js
  test/end-to-end/paths/save-resume.js
Labels: ns:div-pfe-pr-454

#458 Fix failing tests and run every test on Kube
  test/end-to-end/pages/pay/pay-online-only.js
  test/end-to-end/paths/payment.js
  test/end-to-end/paths/reasonsForDivorce.js
  test/end-to-end/paths/save-resume.js
Labels: ns:div-pfe-pr-458

#456 [PREVIEW] wrap changes from DIV-4342 in new desertion feature toggle
  app/steps/grounds-for-divorce/desertion/when-left/index.js
  app/steps/grounds-for-divorce/desertion/when-left/index.test.js
  config/custom-environment-variables.yaml
  config/default.yaml
  infrastructure/main.tf
  infrastructure/output.tf
  infrastructure/preview.tfvars
  infrastructure/variables.tf
  kubernetes/config.aat.yaml
Labels: ns:div-pfe-pr-456
