Repository hmcts/div-petitioner-frontend, pull requests merged in 2019-03, with the labels that each got.

#460 DIV-4106 - Remove the 'temp interstitial' initial page from the journey
  app/middleware/draftPetitionStoreMiddleware.js
  app/steps/authenticated/index.js
  app/steps/authenticated/index.test.js
  app/steps/check-your-answers/index.js
  app/steps/grounds-for-divorce/lived-apart-since/index.test.js
  app/steps/index/content.json
  app/steps/index/index.js
  app/steps/index/index.test.js
  app/steps/index/template.html
  app/steps/screening-questions/has-marriage-broken/content.json
  app/steps/screening-questions/has-marriage-broken/template.html
  app/steps/start/index.js
  app/steps/start/index.test.js
  app/steps/start/template.html
  bin/run-smoke-tests.sh
  config/default.yaml
  package.json
  test/accessibility/a11yTest.js
  test/end-to-end/pages/index/index.js
  test/end-to-end/paths/cookieBanner.js
  test/end-to-end/paths/errorPaths.js
  test/end-to-end/paths/logout.js
  test/end-to-end/paths/reportAProblemPath.js
  test/end-to-end/paths/startSession.js
  test/end-to-end/smoke/smoketest.js
  test/mutation/mutation_steps_k.conf.js
  test/validation/htmlTest.js
Labels: ns:div-pfe-pr-460

#467 DIV-4362: Forced dependency version of braces to remove 2 vulnerabilities
  package.json
  yarn.lock
Labels: ns:div-pfe-pr-467

#407 add new question to 2 year sep
  app/steps/grounds-for-divorce/reason/index.js
  app/steps/grounds-for-divorce/reason/index.test.js
  app/steps/grounds-for-divorce/respondent-consent/index.js
Labels: ns:div-pfe-pr-407

#471 DIV-836 Fixing date validation input
  app/views/common/components/formElements.html
  app/views/common/components/formElements.test.js
Labels: ns:div-pfe-pr-471

#474 Remove security alert on github
  package.json
  yarn.lock
Labels: ns:div-pfe-pr-474

#444 Don't signout on no certificate translated exit page and updated content
  app/core/steps/DestroySessionStep.js
  app/core/steps/DestroySessionStep.test.js
  app/core/steps/ExitStep.js
  app/core/steps/ExitStep.test.js
  app/steps/bye/index.js
  app/steps/check-your-answers/index.js
  app/steps/check-your-answers/index.test.js
  app/steps/done-and-submitted/index.js
  app/steps/exit/about-your-marriage/no-certificate-translated/content.json
  app/steps/exit/about-your-marriage/no-certificate-translated/index.js
  app/steps/exit/about-your-marriage/no-certificate-translated/index.test.js
  app/steps/save-resume/removed-saved-application/index.js
  app/steps/save-resume/save-and-close/index.js
  app/steps/timeout/index.js
  test/end-to-end/paths/foreignMarriageCertificates.js
Labels: ns:div-pfe-pr-444

#476 increase logging for idam express middleware
  package.json
  yarn.lock
Labels: ns:div-pfe-pr-476

#475 Always show files question even if no files there
  app/steps/marriage/upload/partials/checkYourAnswersTemplate.html
Labels: ns:div-pfe-pr-475

#473 change logic so that if case is an amend petition always redirect to …
  app/middleware/draftPetitionStoreMiddleware.js
  app/middleware/draftPetitionStoreMiddleware.test.js
  app/steps/authenticated/index.js
  app/steps/authenticated/index.test.js
Labels: ns:div-pfe-pr-473

#478 Add region specific to run nightly tests on European data centre
  test/end-to-end/saucelabs.conf.js
Labels: ns:div-pfe-pr-478

#479 Upgrade e2e test library
  package.json
  test/end-to-end/paths/basicDivorce.js
  yarn.lock
Labels: ns:div-pfe-pr-479

#483 Downgrade webdriver io
  package.json
  test/crossbrowser/supportedBrowsers.js
  yarn.lock
Labels: ns:div-pfe-pr-483

#480 Migrated grunt-sync to grunt-contrib-copy
  Gruntfile.js
  package.json
  test/end-to-end/saucelabs.conf.js
  yarn.lock
Labels: ns:div-pfe-pr-480

#484 update host name for data centre
  test/end-to-end/saucelabs.conf.js
Labels: ns:div-pfe-pr-484

#472 Setup SAAT and SIDAM
  Jenkinsfile_CNP
  Jenkinsfile_parameterized
  app/services/healthcheck.js
  bin/run-crossbrowser-tests.sh
  bin/run-functional-tests.sh
  infrastructure/aat.tfvars
  infrastructure/main.tf
  infrastructure/preview.tfvars
  infrastructure/saat.tfvars
  infrastructure/sprod.tfvars
  infrastructure/state.tf
  kubernetes/config.aat.yaml
  package.json
  test/end-to-end/helpers/idamHelper.js
  yarn.lock
Labels: ns:div-pfe-pr-472

#469 DIV-4383 - don't allow duplicate cases in non-prod
  app/middleware/redirectMiddleware.js
  app/middleware/redirectMiddleware.test.js
  app/middleware/submissionMiddleware.js
  app/middleware/submissionMiddleware.test.js
  app/services/logger.js
  app/services/logger.test.js
  app/services/submission.js
  app/services/submission.test.js
  app/steps/check-your-answers/index.js
  config/custom-environment-variables.yaml
  config/default.yaml
  infrastructure/aat.tfvars
  infrastructure/demo.tfvars
  infrastructure/main.tf
  infrastructure/output.tf
  infrastructure/preview.tfvars
  infrastructure/prod.tfvars
  infrastructure/saat.tfvars
  infrastructure/sandbox.tfvars
  infrastructure/sprod.tfvars
  infrastructure/variables.tf
  kubernetes/config.aat.yaml
  test/end-to-end/paths/errorPaths.js
Labels: ns:div-pfe-pr-469

#425 DIV-2915: Refactored pages with gender binary variants and updated tests
  app/steps/jurisdiction/interstitial/content.json
  app/steps/respondent/correspondence/send-to-solicitor/content.json
  app/steps/respondent/correspondence/send-to-solicitor/index.test.js
  app/steps/respondent/correspondence/send-to-solicitor/partials/checkYourAnswersTemplate.html
  app/steps/respondent/correspondence/send-to-solicitor/template.html
  app/steps/respondent/correspondence/use-home-address/content.json
  app/steps/respondent/correspondence/use-home-address/index.test.js
  app/steps/respondent/correspondence/use-home-address/partials/checkYourAnswersTemplate.html
  app/steps/respondent/correspondence/use-home-address/template.html
  app/steps/respondent/home/lives-at-last-address/content.json
  app/steps/respondent/home/lives-at-last-address/index.test.js
  app/steps/respondent/home/lives-at-last-address/partials/checkYourAnswersTemplate.html
  app/steps/respondent/home/lives-at-last-address/template.html
  package.json
  test/end-to-end/pages/respondent/lives-at-this-address.js
  test/end-to-end/pages/respondent/send-to-solicitor.js
  yarn.lock
Labels: ns:div-pfe-pr-425

#486 DIV-4469 - remove feature flag test
  test/end-to-end/paths/errorPaths.js
Labels: ns:div-pfe-pr-486

#465 DIV-4364: Revised content for the 'have consent' Question.
  app/steps/grounds-for-divorce/reason/index.js
  app/steps/grounds-for-divorce/reason/index.test.js
  app/steps/grounds-for-divorce/respondent-consent/content.json
  app/steps/grounds-for-divorce/respondent-consent/index.test.js
  app/steps/grounds-for-divorce/respondent-consent/template.html
  config/custom-environment-variables.yaml
  config/default.yaml
  infrastructure/aat.tfvars
  infrastructure/main.tf
  infrastructure/output.tf
  infrastructure/variables.tf
Labels: ns:div-pfe-pr-465

#489 DIV-4364: Replace incorrect feature toggle in e2e tests
  test/end-to-end/paths/reasonsForDivorce.js
Labels: ns:div-pfe-pr-489

#490 DIV-4562: Added 5.3.0 toggle to fix wrong page being shown
  app/steps/grounds-for-divorce/reason/index.js
  app/steps/grounds-for-divorce/reason/index.test.js
  app/steps/grounds-for-divorce/respondent-consent/index.js
  app/steps/grounds-for-divorce/respondent-consent/index.test.js
  config/custom-environment-variables.yaml
  config/default.yaml
  infrastructure/main.tf
  infrastructure/output.tf
  infrastructure/preview.tfvars
  infrastructure/variables.tf
  test/end-to-end/paths/reasonsForDivorce.js
Labels: ns:div-pfe-pr-490
