Repository hmcts/div-petitioner-frontend, pull requests merged in 2020-07, with the labels that each got.

#726 WLA-591: Terraform for Welsh copy changes
  charts/div-pfe/Chart.yaml
  charts/div-pfe/values.yaml
Labels: ns:divorce, prd:div, rel:div-pfe-pr-726

#727 Update Terraform Provider
  infrastructure/main.tf
Labels: ns:divorce, prd:div, rel:div-pfe-pr-727

#729 cookies-error test fix
  test/end-to-end/paths/errorPaths.js
Labels: ns:divorce, prd:div, rel:div-pfe-pr-729

#722 WLA-591: Welsh copy amends
  app/content/common-cy.json
  app/content/common-en.json
  app/content/commonJurisdiction-cy.json
  app/core/steps/Step.js
  app/core/steps/ValidationStep.js
  app/middleware/commonContent.js
  app/steps/application-submitted-awaiting-response/content.json
  app/steps/application-submitted/content.json
  app/steps/contact-divorce-team/content.json
  app/steps/done-and-submitted/content.json
  app/steps/done-and-submitted/template.html
  app/steps/exit/grounds-for-divorce/desertion/agree/content.json
  app/steps/exit/grounds-for-divorce/desertion/date/content.json
  app/steps/exit/screening-questions/has-respondent-address/content.json
  app/steps/grounds-for-divorce/reason/content.json
  app/steps/grounds-for-divorce/reason/template.html
  app/steps/grounds-for-divorce/unreasonable-behaviour/content.json
  app/steps/help/need-help/content.json
  app/steps/jurisdiction/habitual-residence/content.json
  app/steps/marriage/husband-or-wife/content.json
  app/steps/marriage/names/content.json
  app/steps/petitioner/changed-name/content.json
  app/steps/petitioner/confidential/content.json
  app/steps/screening-questions/has-respondent-address/content.json
  bin/run-functional-tests.sh
  config/custom-environment-variables.yaml
  config/default.yaml
  infrastructure/main.tf
  infrastructure/variables.tf
  test/end-to-end/paths/reportAProblemPath.js
Labels: ns:divorce, prd:div, rel:div-pfe-pr-722

#730 Separate content ctx login for testing purposes
  app/core/steps/Step.js
  app/core/steps/Step.test.js
  app/core/steps/ValidationStep.js
Labels: ns:divorce, prd:div, rel:div-pfe-pr-730

#725 RPET-295-Amend-stuck-on-HWF
  app/middleware/draftPetitionStoreMiddleware.js
Labels: ns:divorce, prd:div, rel:div-pfe-pr-725

#728 WLA-591: Remove unused configs
  charts/div-pfe/Chart.yaml
  charts/div-pfe/values.yaml
Labels: ns:divorce, prd:div, rel:div-pfe-pr-728

#733 remove yarn audit as its now run elsewhere
  Jenkinsfile_CNP
Labels: ns:divorce, prd:div, rel:div-pfe-pr-733

#720 WLA-588: Enable Language Preference e2e
  package.json
  test/end-to-end/data/basicDivorceSessionData.js
  test/end-to-end/helpers/SessionHelper.js
  test/end-to-end/paths/aboutYourMarriageCertificate.js
  test/end-to-end/paths/basicDivorce.js
  test/end-to-end/paths/errorPaths.js
  test/end-to-end/paths/exitPaths.js
  test/end-to-end/paths/foreignMarriageCertificates.js
  test/end-to-end/paths/invalidCsrf.js
  test/end-to-end/paths/jurisdictionConnections.js
  test/end-to-end/paths/livingTogether.js
  test/end-to-end/paths/logout.js
  test/end-to-end/paths/payment.js
  test/end-to-end/paths/postcode.js
  test/end-to-end/paths/reasonsForDivorce.js
  test/end-to-end/paths/save-resume.js
  test/end-to-end/paths/uploadMarriageCertificate.js
  yarn.lock
Labels: ns:divorce, prd:div, rel:div-pfe-pr-720

#732 Update content
  app/steps/done-and-submitted/content.json
  app/steps/done-and-submitted/index.test.js
  app/steps/done-and-submitted/template.html
Labels: ns:divorce, prd:div, rel:div-pfe-pr-732

#738 Add link back
  app/steps/done-and-submitted/content.json
Labels: ns:divorce, prd:div, rel:div-pfe-pr-738

#723 PCQ-390: PCQ Integration
  app/core/setup/setupSecrets.js
  app/middleware/completeEqualityTask.js
  app/middleware/completeEqualityTask.test.js
  app/routes/featureToggles.js
  app/steps/equality/content.json
  app/steps/equality/createToken.js
  app/steps/equality/index.js
  app/steps/equality/index.test.js
  app/steps/marriage/upload/index.js
  app/steps/marriage/upload/index.test.js
  charts/div-pfe/Chart.yaml
  charts/div-pfe/values.preview.template.yaml
  charts/div-pfe/values.yaml
  config/custom-environment-variables.yaml
  config/default.yaml
  test/end-to-end/data/basicDivorceSessionData.js
  test/end-to-end/helpers/SessionHelper.js
  test/end-to-end/pages/equality/equality.js
  test/end-to-end/paths/basicDivorce.js
  yarn.lock
Labels: ns:divorce, prd:div, rel:div-pfe-pr-723

#734 Upgrade dependencies to cut down CVE warnings
  audit.json
  package.json
  yarn.lock
Labels: ns:divorce, prd:div, rel:div-pfe-pr-734

#741 Div-6155: PFE awaiting amend landing page
  app.js
  app/assets/images/icon-file-download.png
  app/assets/sass/application.scss
  app/core/utils/checkToggle.js
  app/core/utils/checkToggle.test.js
  app/middleware/evidenceManagementMiddleware.js
  app/middleware/evidenceManagementMiddleware.test.js
  app/middleware/redirectMiddleware.js
  app/middleware/redirectMiddleware.test.js
  app/middleware/submissionMiddleware.js
  app/middleware/submissionMiddleware.test.js
  app/routes/featureToggles.js
  app/services/documentHandler.js
  app/services/documentHandler.test.js
  app/services/evidenceManagementService.js
  app/services/evidenceManagementService.test.js
  app/services/healthcheck.js
  app/steps/amendment-explanatory-page/content.json
  app/steps/amendment-explanatory-page/index.js
  app/steps/amendment-explanatory-page/index.test.js
  app/steps/amendment-explanatory-page/schema.json
  app/steps/amendment-explanatory-page/template.html
  app/steps/authenticated/index.test.js
  app/steps/marriage/upload/index.js
  app/views/common/components/amendmentExplanatoryPageComponents.html
  charts/div-pfe/Chart.yaml
  charts/div-pfe/values.yaml
  config/custom-environment-variables.yaml
  config/default.yaml
  config/example-local-aat.yml
  infrastructure/main.tf
  infrastructure/variables.tf
  package.json
  test/end-to-end/data/basicDivorceSessionData.js
  test/end-to-end/helpers/SessionHelper.js
  test/fixtures/mockAwaitingAmendSession.json
  yarn.lock
Labels: ns:divorce, prd:div, rel:div-pfe-pr-741

#745 Div 6193: Amend case from amendment explanatory page
  app/middleware/submissionMiddleware.js
  app/services/mocks/transformationServiceClient.js
  app/services/submission.js
  app/services/submission.test.js
  app/services/transformationServiceClient.js
  app/services/transformationServiceClient.test.js
  app/steps/amendment-explanatory-page/content.json
  app/steps/amendment-explanatory-page/index.js
  app/steps/amendment-explanatory-page/index.test.js
  app/steps/screening-questions/financial-remedy/index.js
  sonar-project.properties
  test/fixtures/mockAmendedSession.json
Labels: ns:divorce, prd:div, rel:div-pfe-pr-745
