Repository hmcts/div-petitioner-frontend, pull requests merged in 2020-11, with the labels that each got.

#772 Rpet 586 smoke test update
  Jenkinsfile_CNP
  app/core/setup/setupSecrets.js
  app/core/setup/setupSecrets.test.js
  charts/div-pfe/Chart.yaml
  charts/div-pfe/values.yaml
  config/custom-environment-variables.yaml
  config/default.yaml
  config/example-local-aat.yml
  infrastructure/main.tf
  test/end-to-end/pages/index/index.js
  test/end-to-end/smoke.conf.js
  test/end-to-end/smoke/smoketest.js
Labels: ns:divorce, prd:div, rel:div-pfe-pr-772

#777 RPET-586 Smoke test
  app/core/setup/setupSecrets.test.js
  test/end-to-end/codecept.conf.js
  test/end-to-end/pages/index/index.js
  test/end-to-end/paths/jurisdictionConnections.js
  test/end-to-end/paths/reasonsForDivorce.js
  test/end-to-end/smoke.conf.js
  test/end-to-end/smoke/smoketest.js
Labels: ns:divorce, prd:div, rel:div-pfe-pr-777

#769 Chore: e2e and crossbrowser version bumps
  config/default.yaml
  package.json
  test/crossbrowser/supportedBrowsers.js
  test/end-to-end/helpers/ElementExist.js
  test/end-to-end/helpers/JSWait.js
  test/end-to-end/helpers/SauceLabsReportingHelper.js
  test/end-to-end/helpers/SessionHelper.js
  test/end-to-end/paths/reasonsForDivorce.js
  test/end-to-end/saucelabs.conf.js
Labels: ns:divorce, prd:div, rel:div-pfe-pr-769

#779 Fix: Crossbrowser Chrome, Firefox and Edge tests (v2)
  package.json
  test/crossbrowser/supportedBrowsers.js
  test/end-to-end/helpers/GeneralHelpers.js
  test/end-to-end/pages/address/postcode.js
  test/end-to-end/pages/check-your-answers/check-your-answers.js
  test/end-to-end/pages/done-and-submitted/done-and-submitted.js
  test/end-to-end/pages/equality/equality.js
  test/end-to-end/pages/financial/advice.js
  test/end-to-end/pages/financial/arrangements.js
  test/end-to-end/pages/generic-error/generic-error.js
  test/end-to-end/pages/grounds-for-divorce/reason.js
  test/end-to-end/pages/grounds-for-divorce/unreasonable-behaviour.js
  test/end-to-end/pages/help/need-help.js
  test/end-to-end/pages/help/with-fees.js
  test/end-to-end/pages/jurisdiction/habitual-residence.js
  test/end-to-end/pages/jurisdiction/interstitial.js
  test/end-to-end/pages/legal/legal-proceedings.js
  test/end-to-end/pages/living-arrangements/live-together.js
  test/end-to-end/pages/marriage/certificate-names.js
  test/end-to-end/pages/marriage/date.js
  test/end-to-end/pages/marriage/husband-or-wife.js
  test/end-to-end/pages/marriage/married-in-uk.js
  test/end-to-end/pages/marriage/names.js
  test/end-to-end/pages/marriage/upload.js
  test/end-to-end/pages/petitioner/changed-name.js
  test/end-to-end/pages/petitioner/confidential.js
  test/end-to-end/pages/petitioner/contact-details.js
  test/end-to-end/pages/petitioner/use-home-address.js
  test/end-to-end/pages/prayer/claim-costs.js
  test/end-to-end/pages/respondent/use-home-address.js
  test/end-to-end/pages/screening-questions/has-marriage-broken.js
  test/end-to-end/pages/screening-questions/has-marriage-cert.js
  test/end-to-end/pages/screening-questions/has-respondent-address.js
  test/end-to-end/pages/screening-questions/language-preference.js
  test/end-to-end/pages/screening-questions/read-financial-remedy.js
  test/end-to-end/saucelabs.conf.js
  yarn.lock
Labels: ns:divorce, prd:div, rel:div-pfe-pr-779

#778 Improve Logging around redirect to DN
  app/middleware/redirectMiddleware.js
Labels: ns:divorce, prd:div, rel:div-pfe-pr-778

#781 Reduce E2E_WAIT_FOR_TIMEOUT_VALUE for e2e tests
  bin/run-functional-tests.sh
Labels: ns:divorce, prd:div, rel:div-pfe-pr-781

#782 Feature: Add retries to idamHelper.js and some e2e tests
  test/end-to-end/helpers/idamHelper.js
  test/end-to-end/paths/amend.js
  test/end-to-end/paths/serviceApplicationNotApproved.js
Labels: ns:divorce, prd:div, rel:div-pfe-pr-782

#783 Added welsh accessibility check for Petitioner Frontend
  test/accessibility/a11yTest.js
Labels: ns:divorce, prd:div, rel:div-pfe-pr-783

#785 Fix: Crossbrowser IE and Safari tests (v4)
  bin/run-crossbrowser-tests.sh
  config/custom-environment-variables.yaml
  test/crossbrowser/supportedBrowsers.js
  test/end-to-end/helpers/ElementExist.js
  test/end-to-end/helpers/SauceLabsBrowserHelper.js
  test/end-to-end/paths/jurisdictionConnections.js
  test/end-to-end/saucelabs.conf.js
Labels: ns:divorce, prd:div, rel:div-pfe-pr-785

#786 Nightly Crossbrowser improvements
  test/crossbrowser/supportedBrowsers.js
  test/end-to-end/helpers/ElementExist.js
  test/end-to-end/helpers/JSWait.js
  test/end-to-end/helpers/SauceLabsBrowserHelper.js
  test/end-to-end/helpers/idamHelper.js
  test/end-to-end/pages/help/with-fees.js
Labels: ns:divorce, prd:div, rel:div-pfe-pr-786
