Repository hmcts/div-petitioner-frontend, pull requests merged in 2020-02, with the labels that each got.

#652 Fix Pipeline & upgraded Node to 12.14.1
  .nvmrc
  Dockerfile
  README.md
  app/assets/javascripts/.eslintrc
  app/dataStructure.json
  app/services/sessionSerializer.test.js
  docker-compose.yml
  infrastructure/variables.tf
  package.json
  test/end-to-end/codecept.conf.js
  yarn.lock
Labels: ns:divorce, rel:div-pfe-pr-652

#659 Regenerated less strict localhost ssl certificates since node JS 12 s…
  app/resources/localhost-ssl/localhost-ca.crt
  app/resources/localhost-ssl/localhost.crt
  app/resources/localhost-ssl/localhost.key
  yarn.lock
Labels: ns:divorce, rel:div-pfe-pr-659

#660 RPET-58: Remove the deprecated enableDockerBuild() configuration
  Jenkinsfile_CNP
Labels: ns:divorce, rel:div-pfe-pr-660

#661 comment out until we have valid glue
  Jenkinsfile_nightly
Labels: ns:divorce, rel:div-pfe-pr-661

#663 Enable security scan
  Jenkinsfile_nightly
  audit.json
  security.sh
  zapKnownIssues.xml
Labels: ns:divorce, rel:div-pfe-pr-663

#664 Fix cookie authentication test
  charts/div-pfe/values.preview.template.yaml
  test/end-to-end/paths/errorPaths.js
  test/end-to-end/paths/reportAProblemPath.js
Labels: ns:divorce, rel:div-pfe-pr-664

#667 fix failed test
  test/end-to-end/paths/errorPaths.js
Labels: ns:divorce, rel:div-pfe-pr-667

#666 bump up Chart version
  charts/div-pfe/Chart.yaml
Labels: ns:divorce, rel:div-pfe-pr-666

#657 RPET-47: Removing pages and questions about respondent's solicitor.
  README.md
  app/steps/respondent/correspondence/send-to-solicitor/content.json
  app/steps/respondent/correspondence/send-to-solicitor/index.js
  app/steps/respondent/correspondence/send-to-solicitor/index.test.js
  app/steps/respondent/correspondence/send-to-solicitor/partials/checkYourAnswersTemplate.html
  app/steps/respondent/correspondence/send-to-solicitor/schema.json
  app/steps/respondent/correspondence/send-to-solicitor/template.html
  app/steps/respondent/correspondence/use-home-address/content.json
  app/steps/respondent/correspondence/use-home-address/index.js
  app/steps/respondent/correspondence/use-home-address/index.test.js
  app/steps/respondent/correspondence/use-home-address/template.html
  app/steps/respondent/solicitor/address/content.json
  app/steps/respondent/solicitor/address/index.js
  app/steps/respondent/solicitor/address/index.test.js
  app/steps/respondent/solicitor/details/content.json
  app/steps/respondent/solicitor/details/index.js
  app/steps/respondent/solicitor/details/index.test.js
  app/steps/respondent/solicitor/details/schema.json
  app/steps/respondent/solicitor/details/template.html
  test/end-to-end/data/amendPetitionSession.js
  test/end-to-end/pages/respondent/send-to-solicitor.js
  test/end-to-end/pages/respondent/solicitor-details.js
  test/end-to-end/paths/livingTogether.js
  test/fixtures/mockSession.json
Labels: ns:divorce, rel:div-pfe-pr-657

#669 Bumping up version of yarn, as suggested by alert on GitHub.
  package.json
  yarn.lock
Labels: ns:divorce, rel:div-pfe-pr-669
