Repository hmcts/div-petitioner-frontend, pull requests merged in 2020-12, with the labels that each got.

#790 Moved a test to run as part of nightly
  bin/run-functional-tests.sh
  test/end-to-end/paths/errorPaths.js
Labels: ns:divorce, prd:div, rel:div-pfe-pr-790

#791 DIV-6673: Upgrading puppeteer to try and fix pipeline issues.
  .github/PULL_REQUEST_TEMPLATE.md
  README.md
  config/example-local-aat.yml
  package.json
  yarn.lock
Labels: ns:divorce, prd:div, rel:div-pfe-pr-791

#793 DIV-6673: Updating test to treat preview and non-preview URL equally
  test/end-to-end/paths/errorPaths.js
Labels: ns:divorce, prd:div, rel:div-pfe-pr-793

#794 DIV-6677/DIV-6673: Skipping test to get a green build and satisfy the QA readiness report
  test/end-to-end/paths/errorPaths.js
Labels: ns:divorce, prd:div, rel:div-pfe-pr-794

#796 Really skipping test
  test/end-to-end/paths/errorPaths.js
Labels: ns:divorce, prd:div, rel:div-pfe-pr-796

#789 DIV-6608: Accept new states on PFE
  app/middleware/submissionMiddleware.test.js
  app/steps/done-and-submitted/index.js
  app/steps/done-and-submitted/index.test.js
  config/default.yaml
  package.json
  test/examples/courts/courts.json
  yarn.lock
Labels: ns:divorce, prd:div, rel:div-pfe-pr-789
