Repository hmcts/div-petitioner-frontend, pull requests merged in 2020-10, with the labels that each got.

#752 RPET-359-Welsh-language-question-change
  app/steps/screening-questions/language-preference/content.json
  app/steps/screening-questions/language-preference/template.html
  app/views/common/components/formElements.html
Labels: ns:divorce, prd:div, rel:div-pfe-pr-752

#756 upgrade AzureRM
  infrastructure/.terraform-version
  infrastructure/main.tf
  infrastructure/output.tf
  infrastructure/state.tf
  infrastructure/variables.tf
Labels: ns:divorce, prd:div, rel:div-pfe-pr-756

#758 Fixed Pa11y Test
  package.json
Labels: ns:divorce, prd:div, rel:div-pfe-pr-758

#759 TA-46-Basic-reasons-E2E Tests
  functional-output/.gitignore
  test/end-to-end/codecept.conf.js
  test/end-to-end/paths/basicDivorce.en.test.js
  test/end-to-end/paths/reasonsForDivorce.js
  test/end-to-end/paths/reasonsForDivorceEn.js
  test/end-to-end/saucelabs.conf.js
Labels: ns:divorce, prd:div, rel:div-pfe-pr-759

#760 TA-143 functional tests fix
  package.json
  test/end-to-end/codecept.conf.js
  test/end-to-end/pages/generic-error/generic-error.js
  test/end-to-end/paths/aboutYourMarriageCertificate.js
  test/end-to-end/paths/amend.js
  test/end-to-end/paths/basicDivorce.js
  test/end-to-end/paths/cookieBanner.js
  test/end-to-end/paths/errorPaths.js
  test/end-to-end/paths/exitPaths.js
  test/end-to-end/paths/foreignMarriageCertificates.js
  test/end-to-end/paths/invalidCsrf.js
  test/end-to-end/paths/jurisdictionConnections.js
  test/end-to-end/paths/livingTogether.js
  test/end-to-end/paths/logout.js
  test/end-to-end/paths/payment.js
  test/end-to-end/paths/postcode.js
  test/end-to-end/paths/reasonsForDivorce.js
  test/end-to-end/paths/reportAProblemPath.js
  test/end-to-end/paths/save-resume.js
  test/end-to-end/paths/serviceApplicationNotApproved.js
  test/end-to-end/paths/startSession.js
  test/end-to-end/paths/staticPages.js
  test/end-to-end/paths/uploadMarriageCertificate.js
  test/end-to-end/saucelabs.conf.js
Labels: ns:divorce, prd:div, rel:div-pfe-pr-760

#763 TA-145-redirect to login page test fix
  test/end-to-end/codecept.conf.js
  test/end-to-end/paths/errorPaths.js
Labels: ns:divorce, prd:div, rel:div-pfe-pr-763

#764 Added Adultery, Desertion and exit scenarios
  test/end-to-end/pages/prayer/claim-costs.js
  test/end-to-end/paths/adulteryAndDesertionJourneys.js
  test/end-to-end/paths/exitScenarios.js
Labels: ns:divorce, prd:div, rel:div-pfe-pr-764

#765 Adding Keep my address private functionality
  test/end-to-end/pages/petitioner/confidential.js
  test/end-to-end/pages/prayer/claim-costs.js
  test/end-to-end/paths/adulteryAndDesertionJourneys.js
Labels: ns:divorce, prd:div, rel:div-pfe-pr-765
