Repository hmcts/div-petitioner-frontend, pull requests merged in 2021-03, with the labels that each got.

#816 DIV-6781: PFE landing pages for AosDrafted
  app.js
  app/core/utils/checkToggle.js
  app/core/utils/checkToggle.test.js
  app/middleware/submissionMiddleware.js
  app/middleware/submissionMiddleware.test.js
  app/routes/featureToggles.js
  app/steps/done-and-submitted/content.json
  app/steps/done-and-submitted/template.html
  config/default.yaml
  package.json
  test/end-to-end/data/aosDraftedSession.js
  test/end-to-end/data/basicDivorceSessionData.js
  test/end-to-end/data/serviceApplicationNotApprovedSession.js
  test/end-to-end/helpers/SessionHelper.js
  test/end-to-end/paths/aosDrafted.js
  yarn.lock
Labels: ns:divorce, prd:div, rel:div-pfe-pr-816

#829 Refactoring for DIV-6760
  app/steps/respondent/correspondence/send-to-solicitor/content.json
  app/steps/respondent/correspondence/send-to-solicitor/index.js
  app/steps/respondent/correspondence/send-to-solicitor/index.test.js
  app/steps/respondent/correspondence/send-to-solicitor/template.html
  app/steps/respondent/correspondence/use-home-address/content.json
  app/steps/respondent/correspondence/use-home-address/index.js
  app/steps/respondent/correspondence/use-home-address/index.test.js
  app/steps/respondent/correspondence/use-home-address/template.html
  test/end-to-end/pages/respondent/send-to-solicitor.js
  test/end-to-end/pages/respondent/use-home-address.js
Labels: ns:divorce, prd:div, rel:div-pfe-pr-829

#831 DIV-6836: Using new div-idam-test-harness
  package.json
  test/end-to-end/helpers/idamHelper.js
  yarn.lock
Labels: ns:divorce, prd:div, rel:div-pfe-pr-831

#830 DIV-6760: Solicitor email mandatory during organisation lookup
  app/core/utils/respondentSolicitorSearchHelper.js
  app/core/utils/respondentSolicitorSearchHelper.test.js
  app/steps/respondent/correspondence/solicitor-search/content.json
  app/steps/respondent/correspondence/solicitor-search/index.js
  app/steps/respondent/correspondence/solicitor-search/index.test.js
  app/views/common/components/respondentSolicitorComponents.html
  test/end-to-end/pages/organisation-search/search.js
Labels: Based off another branch, ns:divorce, prd:div, rel:div-pfe-pr-830

#819 DIV-6816: changes to direct petitioner to respondent solictor page
  app/steps/respondent/correspondence/send-to-solicitor/content.json
  app/steps/respondent/correspondence/send-to-solicitor/index.js
  app/steps/respondent/correspondence/send-to-solicitor/index.test.js
  app/steps/respondent/correspondence/send-to-solicitor/schema.json
  app/steps/respondent/correspondence/send-to-solicitor/template.html
  app/steps/respondent/correspondence/use-home-address/content.json
  app/steps/respondent/correspondence/use-home-address/index.js
  app/steps/respondent/correspondence/use-home-address/index.test.js
  app/steps/respondent/correspondence/use-home-address/template.html
  app/steps/respondent/solicitor/details/content.json
  app/steps/respondent/solicitor/details/index.js
  app/steps/respondent/solicitor/details/schema.json
  app/steps/respondent/solicitor/details/template.html
  config/default.yaml
  test/end-to-end/helpers/SessionHelper.js
  test/end-to-end/pages/respondent/send-to-solicitor.js
  test/end-to-end/pages/respondent/use-home-address.js
Labels: ns:divorce, prd:div, rel:div-pfe-pr-819

#834 DIV-6831: Added scrollbars to 'search solicitor organisation' results
  app/assets/sass/_organisation-search.scss
  app/assets/sass/application.scss
  app/views/common/components/respondentSolicitorComponents.html
Labels: ns:divorce, prd:div, rel:div-pfe-pr-834

#838 Moved some functional tests to nightly build stage
  package.json
  test/end-to-end/paths/aboutYourMarriageCertificate.js
  test/end-to-end/paths/adulteryAndDesertion-cy.js
  test/end-to-end/paths/adulteryAndDesertion-en.js
  test/end-to-end/paths/adulteryAndDesertion.js
  test/end-to-end/paths/aosDrafted.js
  test/end-to-end/paths/cookieBanner.js
  test/end-to-end/paths/errorPaths.js
  test/end-to-end/paths/exitScenarios.js
  test/end-to-end/paths/invalidCsrf.js
  test/end-to-end/paths/logout.js
  test/end-to-end/paths/reasonsForDivorce.js
  test/end-to-end/paths/reportAProblemPath.js
  test/end-to-end/paths/startSession.js
  test/end-to-end/paths/staticPages.js
  test/end-to-end/paths/uploadMarriageCertificate.js
Labels: ns:divorce, prd:div, rel:div-pfe-pr-838

#821 DIV-6760,6758,6824: respondent solicitor
  README.md
  app/core/utils/respondentSolicitorSearchHelper.js
  app/core/utils/respondentSolicitorSearchHelper.test.js
  app/steps/respondent/correspondence/solicitor-search/content.json
  app/steps/respondent/correspondence/solicitor-search/index.js
  app/steps/respondent/correspondence/solicitor-search/schema.json
  app/views/common/components/respondentSolicitorDetailComponents.html
Labels: ns:divorce, prd:div, rel:div-pfe-pr-821

#837 DIV-6760,6758,6824: respondent solicitor
  README.md
  app/assets/sass/_organisation-search.scss
  app/assets/sass/application.scss
  app/core/utils/respondentSolicitorSearchHelper.js
  app/core/utils/respondentSolicitorSearchHelper.test.js
  app/services/mocks/organisationServiceClient.js
  app/services/mocks/responses/organisations.json
  app/services/organisationService.js
  app/services/organisationService.test.js
  app/steps/respondent/correspondence/send-to-solicitor/index.js
  app/steps/respondent/correspondence/solicitor-search/content.json
  app/steps/respondent/correspondence/solicitor-search/index.js
  app/steps/respondent/correspondence/solicitor-search/index.test.js
  app/steps/respondent/correspondence/solicitor-search/partials/checkYourAnswersTemplate.html
  app/steps/respondent/correspondence/solicitor-search/schema.json
  app/steps/respondent/correspondence/solicitor-search/template.html
  app/steps/respondent/correspondence/use-home-address/index.js
  app/steps/respondent/correspondence/use-home-address/index.test.js
  app/steps/respondent/solicitor/details/content.json
  app/steps/respondent/solicitor/details/index.js
  app/steps/respondent/solicitor/details/schema.json
  app/steps/respondent/solicitor/details/template.html
  app/views/common/components/respondentSolicitorComponents.html
  app/views/common/components/respondentSolicitorDetailComponents.html
  app/views/common/errors.html
  config/default.yaml
  package.json
  test/end-to-end/helpers/SessionHelper.js
  test/end-to-end/pages/organisation-search/manual.js
  test/end-to-end/pages/organisation-search/search.js
  test/end-to-end/pages/respondent/use-home-address.js
  test/end-to-end/paths/adulteryAndDesertion-en.js
  yarn.lock
Labels: ns:divorce, prd:div, rel:div-pfe-pr-837

#835 DIV-5457:Add IssuedToBailiff and AwaitingBailiffService states for new page
  app/middleware/submissionMiddleware.js
  app/middleware/submissionMiddleware.test.js
  app/steps/issued-to-bailiff/content.json
  app/steps/issued-to-bailiff/index.js
  app/steps/issued-to-bailiff/index.test.js
  app/steps/issued-to-bailiff/template.html
  test/end-to-end/data/issuedToBailiffSession.js
  test/end-to-end/helpers/SessionHelper.js
  test/end-to-end/paths/IssuedToBailiff.js
Labels: ns:divorce, prd:div, rel:div-pfe-pr-835

#840 Div 5457 add valid states
  app/middleware/redirectMiddleware.test.js
  config/default.yaml
Labels: ns:divorce, prd:div, rel:div-pfe-pr-840

#839 DIV-6760: Adjusting validation for solicitor email manual
  app/core/utils/respondentSolicitorSearchHelper.js
  app/core/utils/respondentSolicitorSearchHelper.test.js
  app/steps/respondent/correspondence/solicitor-search/content.json
  app/steps/respondent/correspondence/solicitor-search/schema.json
  app/views/common/components/respondentSolicitorDetailComponents.html
Labels: ns:divorce, prd:div, rel:div-pfe-pr-839

#842 DIV-6837: Update check your answers page for respondent solicitor details
  app/core/utils/respondentSolicitorSearchHelper.js
  app/core/utils/respondentSolicitorSearchHelper.test.js
  app/steps/respondent/correspondence/solicitor-search/index.js
  app/steps/respondent/correspondence/solicitor-search/index.test.js
  app/steps/respondent/correspondence/solicitor-search/partials/checkYourAnswersTemplate.html
  app/steps/respondent/correspondence/use-home-address/index.js
  app/steps/respondent/correspondence/use-home-address/index.test.js
  app/steps/respondent/correspondence/use-home-address/partials/checkYourAnswersTemplate.html
Labels: ns:divorce, prd:div, rel:div-pfe-pr-842

#843 DIV-5457-Add downloadable files to session
  app/steps/issued-to-bailiff/index.js
  app/steps/issued-to-bailiff/index.test.js
  test/fixtures/mockIssuedToBailiffSession.json
Labels: ns:divorce, prd:div, rel:div-pfe-pr-843

#844 PRD api url setup differently for different envs
  Jenkinsfile_CNP
  app/services/organisationService.js
  app/services/organisationService.test.js
  bin/run-functional-tests.sh
  charts/div-pfe/values.preview.template.yaml
  config/custom-environment-variables.yaml
  test/end-to-end/smoke.conf.js
Labels: ns:divorce, prd:div, rel:div-pfe-pr-844

#847 Rpet 664 citizen jurisdiction brexit v2
  app/content/commonJurisdiction-en.json
  app/services/jurisdiction/connections.js
  app/services/jurisdiction/content.json
  app/steps/jurisdiction/connection-summary/content.json
  app/steps/jurisdiction/connection-summary/index.test.js
  app/steps/jurisdiction/domicile/index.js
  app/steps/jurisdiction/habitual-residence/index.js
  app/steps/jurisdiction/interstitial/content.json
  app/steps/jurisdiction/jurisdiction.component.test.js
  app/steps/jurisdiction/last-habitual-residence/index.js
  app/steps/jurisdiction/last-habitual-residence/index.test.js
  app/steps/jurisdiction/last-resort/index.test.js
  app/steps/jurisdiction/last-resort/schema.json
  app/steps/jurisdiction/last-resort/template.html
  app/steps/jurisdiction/last-six-months/index.test.js
  app/steps/jurisdiction/residual/content.json
  app/steps/jurisdiction/residual/index.test.js
  app/steps/jurisdiction/residual/template.html
  app/views/common/components/helpConnections.html
  test/end-to-end/helpers/GeneralHelpers.js
Labels: ns:divorce, prd:div, rel:div-pfe-pr-847
