Repository hmcts/div-petitioner-frontend, pull requests merged in 2021-04, with the labels that each got.

#850 DIV-6850:Welsh translation in PFE for solicitor journey pages
  app/steps/respondent/correspondence/send-to-solicitor/content.json
  app/steps/respondent/correspondence/solicitor-search/content.json
  app/steps/respondent/correspondence/use-home-address/content.json
Labels: ns:divorce, prd:div, rel:div-pfe-pr-850

#852 DIV-6850-Add Welsh translation for searchNoOptionFoundText
  app/steps/respondent/correspondence/solicitor-search/content.json
Labels: ns:divorce, prd:div, rel:div-pfe-pr-852

#854 DIV-6850-Add-new-question-in-Welsh
  app/steps/respondent/correspondence/send-to-solicitor/content.json
Labels: ns:divorce, prd:div, rel:div-pfe-pr-854

#856 DIV-6850 - Add missing question mark
  app/steps/respondent/correspondence/send-to-solicitor/content.json
Labels: ns:divorce, prd:div, rel:div-pfe-pr-856

#855 DIV-6881: Resolve Solicitor Search screen functionality when amends scenario
  .gitignore
  app/core/utils/respondentSolicitorSearchHelper.js
  app/core/utils/respondentSolicitorSearchHelper.test.js
  app/steps/respondent/correspondence/solicitor-search/index.js
  app/steps/respondent/correspondence/solicitor-search/index.test.js
  app/steps/respondent/correspondence/use-home-address/index.js
  package.json
Labels: ns:divorce, prd:div, rel:div-pfe-pr-855

#858 DIV-6880: Adding logic for bailiff scenario. Service application not approved landing page
  app/steps/service-application-not-approved/content.json
  app/steps/service-application-not-approved/index.js
  app/steps/service-application-not-approved/index.test.js
Labels: ns:divorce, prd:div, rel:div-pfe-pr-858

#857 DIV-6872: Map respondent solicitor changes to petitioner amend journey
  app/core/utils/respondentSolicitorSearchHelper.js
  app/core/utils/respondentSolicitorSearchHelper.test.js
  app/steps/respondent/correspondence/solicitor-search/index.js
  app/steps/respondent/correspondence/solicitor-search/index.test.js
  app/steps/respondent/correspondence/solicitor-search/partials/checkYourAnswersTemplate.html
  app/steps/respondent/correspondence/solicitor-search/template.html
  app/views/common/components/customPageComponents.html
  test/util/petitionTestHelper.js
Labels: ns:divorce, prd:div, rel:div-pfe-pr-857

#811 Changes for RPET-759. Replacing Google analytics scripts with Google …
  app.js
  app/views/includes/head.html
Labels: ns:divorce, prd:div, rel:div-pfe-pr-811

#814 Changes for RPET-647 - changed 'English and Welsh' option to 'Welsh/E…
  app/steps/screening-questions/language-preference/content.json
  package.json
Labels: ns:divorce, prd:div, rel:div-pfe-pr-814

#859 DIV-6895: Setting respondentSolicitorRepresented and resetting it whe…
  app/core/utils/respondentSolicitorSearchHelper.js
  app/core/utils/respondentSolicitorSearchHelper.test.js
  yarn.lock
Labels: ns:divorce, prd:div, rel:div-pfe-pr-859

#861 unskip tests
  app/steps/grounds-for-divorce/separation-date/index.test.js
Labels: ns:divorce, prd:div, rel:div-pfe-pr-861

#864 DIV-6907: Enabling IDAM feature for nightly pipeline
  Jenkinsfile_CNP
  Jenkinsfile_nightly
  bin/run-crossbrowser-tests.sh
  test/end-to-end/pages/index/index.js
Labels: ns:divorce, prd:div, rel:div-pfe-pr-864

#867 DIV-6907: Renaming cross-browser-test annotation and making amount of…
  package.json
  test/end-to-end/paths/IssuedToBailiff.js
  test/end-to-end/paths/aboutYourMarriageCertificate.js
  test/end-to-end/paths/adulteryAndDesertion-cy.js
  test/end-to-end/paths/cookieBanner.js
  test/end-to-end/paths/errorPaths.js
  test/end-to-end/paths/exitScenarios.js
  test/end-to-end/paths/invalidCsrf.js
  test/end-to-end/paths/logout.js
  test/end-to-end/paths/reasonsForDivorce.js
  test/end-to-end/paths/reportAProblemPath.js
  test/end-to-end/paths/startSession.js
  test/end-to-end/paths/staticPages.js
  test/end-to-end/paths/uploadMarriageCertificate.js
Labels: ns:divorce, prd:div, rel:div-pfe-pr-867

#868 DIV-6907: Making full funcional tests step test all test scenarios
  bin/run-full-functional-tests.sh
  package.json
Labels: ns:divorce, prd:div, rel:div-pfe-pr-868

#870 DIV-6907: Fixing at least a few tests
  Jenkinsfile_nightly
  package.json
  test/end-to-end/pages/marriage/upload.js
  test/end-to-end/pages/screening-questions/language-preference.js
  test/end-to-end/paths/startSession.js
  test/end-to-end/paths/staticPages.js
  test/end-to-end/paths/uploadMarriageCertificate.js
  test/end-to-end/saucelabs.conf.js
  yarn.lock
Labels: ns:divorce, prd:div, rel:div-pfe-pr-870

#873 DIV-6907: Making improvements and fixes in existing tests
  test/end-to-end/pages/address/postcode.js
  test/end-to-end/pages/exit/save-and-close.js
  test/end-to-end/pages/financial/advice.js
  test/end-to-end/pages/financial/arrangements.js
  test/end-to-end/pages/grounds-for-divorce/adultery-3rd-party-details.js
  test/end-to-end/pages/grounds-for-divorce/adultery-details.js
  test/end-to-end/pages/grounds-for-divorce/adultery-second-hand-info.js
  test/end-to-end/pages/grounds-for-divorce/adultery-when.js
  test/end-to-end/pages/grounds-for-divorce/adultery-where.js
  test/end-to-end/pages/grounds-for-divorce/adultery-wish-to-name.js
  test/end-to-end/pages/grounds-for-divorce/desertion-agree.js
  test/end-to-end/pages/grounds-for-divorce/desertion-date.js
  test/end-to-end/pages/grounds-for-divorce/desertion-details.js
  test/end-to-end/pages/grounds-for-divorce/lived-apart-since.js
  test/end-to-end/pages/grounds-for-divorce/reason.js
  test/end-to-end/pages/grounds-for-divorce/respondent-consent.js
  test/end-to-end/pages/grounds-for-divorce/separation-date-new.js
  test/end-to-end/pages/grounds-for-divorce/unreasonable-behaviour.js
  test/end-to-end/pages/help/need-help.js
  test/end-to-end/pages/help/with-fees.js
  test/end-to-end/pages/jurisdiction/habitual-residence.js
  test/end-to-end/pages/jurisdiction/interstitial.js
  test/end-to-end/pages/legal/legal-proceedings.js
  test/end-to-end/pages/living-arrangements/live-together.js
  test/end-to-end/pages/marriage/certificate-names.js
  test/end-to-end/pages/marriage/date.js
  test/end-to-end/pages/marriage/husband-or-wife.js
  test/end-to-end/pages/marriage/married-in-uk.js
  test/end-to-end/pages/marriage/names.js
  test/end-to-end/pages/marriage/upload.js
  test/end-to-end/pages/pay/pay-online-only.js
  test/end-to-end/pages/petitioner/changed-name.js
  test/end-to-end/pages/petitioner/confidential.js
  test/end-to-end/pages/petitioner/contact-details.js
  test/end-to-end/pages/petitioner/use-home-address.js
  test/end-to-end/pages/prayer/claim-costs.js
  test/end-to-end/pages/respondent/use-home-address.js
  test/end-to-end/pages/screening-questions/has-marriage-broken.js
  test/end-to-end/pages/screening-questions/has-marriage-cert.js
  test/end-to-end/pages/screening-questions/has-respondent-address.js
  test/end-to-end/pages/screening-questions/language-preference.js
  test/end-to-end/pages/screening-questions/read-financial-remedy.js
  test/end-to-end/paths/adulteryAndDesertion-cy.js
  test/end-to-end/paths/logout.js
  test/end-to-end/paths/reasonsForDivorce.js
  test/end-to-end/paths/save-resume.js
Labels: ns:divorce, prd:div, rel:div-pfe-pr-873

#874 DIV-6907: Trying to fix sign out feature tests
  app/routes/sign-out.js
  config/development_template.yaml
  package.json
  test/end-to-end/paths/logout.js
  yarn.lock
Labels: ns:divorce, prd:div, rel:div-pfe-pr-874

#876 Checking basic divorce scenario runs on Jenkins
  test/end-to-end/pages/screening-questions/has-respondent-address.js
  test/end-to-end/paths/basicDivorce.js
  test/end-to-end/paths/logout.js
Labels: ns:divorce, prd:div, rel:div-pfe-pr-876

#878 DIV-6907: Hardcoding divorce reason
  test/end-to-end/paths/basicDivorce.js
  test/end-to-end/paths/save-resume.js
Labels: ns:divorce, prd:div, rel:div-pfe-pr-878

#886 DIV-6907: Fixing nightly tests
  test/end-to-end/pages/index/index.js
  test/end-to-end/pages/marriage/date.js
  test/end-to-end/pages/petitioner/confidential.js
  test/end-to-end/paths/adulteryAndDesertion-en.js
  test/end-to-end/paths/invalidCsrf.js
Labels: ns:divorce, prd:div, rel:div-pfe-pr-886
