Repository hmcts/div-petitioner-frontend, pull requests merged in 2021-11, with the labels that each got.

#923 DFR-656 cookie security Fortify fix
  app/middleware/checkCookiesAllowed.js
Labels: ns:divorce, prd:div, rel:div-pfe-pr-923

#925 Update dependencies
  package.json
  yarn-audit-known-issues
  yarn.lock
Labels: ns:divorce, prd:div, rel:div-pfe-pr-925

#927 Upgrade properties-volume
  package.json
  yarn.lock
Labels: ns:divorce, prd:div, rel:div-pfe-pr-927
