Repository hmcts/div-petitioner-frontend, pull requests merged in 2021-05, with the labels that each got.

#888 RPET-981: Fix dependency checks
  package.json
  yarn.lock
Labels: ns:divorce, prd:div, rel:div-pfe-pr-888

#889 Enforce div pay client version
  package.json
  yarn.lock
Labels: ns:divorce, prd:div, rel:div-pfe-pr-889

#892 hosted-git-info and underscore updated
  package.json
  yarn.lock
Labels: ns:divorce, prd:div, rel:div-pfe-pr-892

#893 fix sonar issue
  app/views/cookie-error.html
Labels: ns:divorce, prd:div, rel:div-pfe-pr-893

#894 Temporarily suppress to see if everything else works
  yarn-audit-known-issues
Labels: ns:divorce, prd:div, rel:div-pfe-pr-894
