Repository hmcts/div-petitioner-frontend, pull requests merged in 2021-09, with the labels that each got.

#905 DFR-65: Fix tar vulnerablities
  charts/div-pfe/Chart.yaml
  package.json
  yarn.lock
Labels: ns:divorce, prd:div, rel:div-pfe-pr-905

#907 DFR-556 - Bump superagent-proxy 2.1.0 -> 3.0.0
  config/default.yaml
  package.json
  test/end-to-end/saucelabs.conf.js
  yarn.lock
Labels: ns:divorce, prd:div, rel:div-pfe-pr-907

#908 DFR-437-FEEUPDATE
  app/middleware/submissionMiddleware.test.js
  app/services/mocks/feesAndPaymentsService.js
  app/services/mocks/payment.js
  app/services/payment.test.js
  app/services/submission.test.js
  app/steps/done-and-submitted/index.js
  app/steps/done-and-submitted/index.test.js
  app/steps/financial/arrangements/content.json
  app/steps/financial/arrangements/index.js
  app/steps/financial/arrangements/index.test.js
  app/steps/help/need-help/index.js
  app/steps/help/need-help/index.test.js
  app/steps/pay/pay-online-only/index.js
  app/steps/pay/pay-online-only/index.test.js
  app/steps/service-application-not-approved/index.test.js
  config/custom-environment-variables.yaml
  config/default.yaml
  test/end-to-end/pages/pay/by-card-online-on-govpay.js
  test/end-to-end/pages/pay/pay-online-only.js
  test/end-to-end/paths/payment.js
  test/fixtures/mockAwaitingAmendSession.json
  test/fixtures/mockIssuedToBailiffSession.json
  test/fixtures/mockServiceRefusalSession.json
Labels: ns:divorce, prd:div, rel:div-pfe-pr-908

#911 DFR-435: Switch on fees
  app/services/mocks/feesAndPaymentsService.js
  app/steps/pay/pay-online-only/index.js
  app/steps/pay/pay-online-only/index.test.js
  app/steps/service-application-not-approved/index.js
  app/steps/service-application-not-approved/index.test.js
  charts/div-pfe/Chart.yaml
  charts/div-pfe/values.yaml
  config/default.yaml
Labels: ns:divorce, prd:div, rel:div-pfe-pr-911

#913 Dfr 437 disble payment test
  test/end-to-end/paths/payment.js
Labels: ns:divorce, prd:div, rel:div-pfe-pr-913
