Repository hmcts/div-petitioner-frontend, pull requests merged in 2022-01, with the labels that each got.

#933 DFR-562: Fix Antenna issues
  app/steps/avaya-webchat/template.html
  package.json
  yarn-audit-known-issues
  yarn.lock
Labels: ns:divorce, prd:div, rel:div-pfe-pr-933

#934 fix nightly build dependency checks
  yarn-audit-known-issues
  yarn.lock
Labels: ns:divorce, prd:div, rel:div-pfe-pr-934

#895 DFR-37 deploy cookie banner
  README.md
  app.js
  app/assets/javascripts/cookiesManager.js
  app/assets/javascripts/showHideContent.js
  app/assets/sass/_cookies.scss
  app/assets/sass/application.scss
  app/assets/sass/gov-uk-frontend-toolkit-backward-compatable.scss
  app/core/steps/Step.js
  app/core/steps/Step.test.js
  app/services/sessionSerializer.test.js
  app/steps/grounds-for-divorce/lived-apart-since/template.html
  app/steps/screening-questions/financial-remedy/index.js
  app/steps/screening-questions/has-marriage-broken/content.json
  app/steps/screening-questions/has-marriage-broken/template.html
  app/steps/screening-questions/has-marriage-cert/index.js
  app/steps/screening-questions/language-preference/content.json
  app/steps/screening-questions/language-preference/template.html
  app/steps/service-application-not-approved/index.js
  app/steps/terms-and-conditions/index.js
  app/views/common/components/formElements.html
  app/views/cookie-error.html
  app/views/cookie.html
  app/views/includes/cookies/button/macro.njk
  app/views/includes/cookies/button/template.njk
  app/views/includes/cookies/cookie-banner/cookie.njk
  app/views/includes/cookies/cookie-banner/macro.njk
  app/views/includes/cookies/cookie-banner/template.njk
  app/views/includes/cookies/cookie-manager/cookie-banner.njk
  app/views/includes/cookies/cookie-manager/cookie-reject-all-banner.njk
  app/views/includes/cookies/cookie-manager/cookie-success-all-banner.njk
  app/views/includes/cookies/cookie-manager/cookie-success-banner.njk
  app/views/layout.html
  charts/div-pfe/Chart.yaml
  charts/div-pfe/values.preview.template.yaml
  charts/div-pfe/values.yaml
  config/custom-environment-variables.yaml
  config/default.yaml
  package.json
  test/end-to-end/pages/index/index.js
  test/end-to-end/pages/marriage/upload.js
  test/end-to-end/paths/cookieBanner.js
  test/end-to-end/paths/staticPages.js
  webpack.config.js
  yarn-audit-known-issues
  yarn.lock
Labels: ns:divorce, prd:div, rel:div-pfe-pr-895

#938 Fix Fortify
  app.js
Labels: ns:divorce, prd:div, rel:div-pfe-pr-938

#940 fix failing functional test
  test/end-to-end/pages/pay/pay-online-only.js
Labels: ns:divorce, prd:div, rel:div-pfe-pr-940

#941 DFR-37-Webchat-Fix
  app/assets/javascripts/cookiesManager.js
  yarn.lock
Labels: ns:divorce, prd:div, rel:div-pfe-pr-941

#939 Dfr 37 Restore OG Cookie Banner when Dynatrace is Disabled
  app/steps/screening-questions/has-marriage-broken/content.json
  app/steps/screening-questions/has-marriage-broken/template.html
  app/steps/screening-questions/language-preference/content.json
  app/steps/screening-questions/language-preference/template.html
Labels: ns:divorce, prd:div, rel:div-pfe-pr-939

#944 Resolve header manipulation fortify errors
  app/assets/javascripts/cookiesManager.js
  yarn-audit-known-issues
Labels: ns:divorce, prd:div, rel:div-pfe-pr-944

#947 fix vulnerabilities
  yarn-audit-known-issues
Labels: ns:divorce, prd:div, rel:div-pfe-pr-947

#948 fix failing Ft test
  test/end-to-end/paths/errorPaths.js
Labels: ns:divorce, prd:div, rel:div-pfe-pr-948
