Repository hmcts/div-petitioner-frontend, pull requests merged in 2022-03, with the labels that each got.

#985 Update dependencies
  .nvmrc
  Gruntfile.js
  app/services/sessionSerializer.test.js
  infrastructure/variables.tf
  package.json
  test/validation/htmlTest.js
  webpack.config.js
  yarn-audit-known-issues
  yarn.lock
Labels: ns:divorce, prd:div, rel:div-pfe-pr-985

#964 Add new application cutoff banner
  app.js
  app/assets/sass/_new-application-cutoff-date-banner.scss
  app/assets/sass/application.scss
  app/views/includes/new-application-cutoff-date-banner.html
  app/views/layout.html
  charts/div-pfe/Chart.yaml
  charts/div-pfe/values.preview.template.yaml
  charts/div-pfe/values.yaml
  config/custom-environment-variables.yaml
  config/default.yaml
  server.js
  yarn-audit-known-issues
Labels: ns:divorce, prd:div, rel:div-pfe-pr-964

#987 Update yarn-audit-known-issues
  yarn-audit-known-issues
Labels: ns:divorce, prd:div, rel:div-pfe-pr-987

#988 Update yarn-audit-known-issues
  yarn-audit-known-issues
Labels: ns:divorce, prd:div, rel:div-pfe-pr-988

#989 Update yarn audit known issues
  yarn-audit-known-issues
Labels: ns:divorce, prd:div, rel:div-pfe-pr-989

#990 Update yarn audit known issues
  yarn-audit-known-issues
Labels: ns:divorce, prd:div, rel:div-pfe-pr-990

#995 Update yarn audit known issues
  yarn-audit-known-issues
Labels: ns:divorce, prd:div, rel:div-pfe-pr-995

#996 Update Chart.yaml
  charts/div-pfe/Chart.yaml
Labels: ns:divorce, prd:div, rel:div-pfe-pr-996

#999 update deps
  package.json
  yarn.lock
Labels: ns:divorce, prd:div, rel:div-pfe-pr-999

#992 Dfr 885 pre nfd landing page
  app/middleware/redirectMiddleware.js
  app/middleware/redirectMiddleware.test.js
  app/steps/cutoff-landing-page/content.json
  app/steps/cutoff-landing-page/index.js
  app/steps/cutoff-landing-page/index.test.js
  app/steps/cutoff-landing-page/template.html
  charts/div-pfe/Chart.yaml
  charts/div-pfe/values.preview.template.yaml
  charts/div-pfe/values.yaml
  config/custom-environment-variables.yaml
  config/default.yaml
  sonar-project.properties
  test/end-to-end/codecept.conf.js
  test/end-to-end/paths/aboutYourMarriageCertificate.disabled
  test/end-to-end/paths/adulteryAndDesertion-cy.disabled
  test/end-to-end/paths/adulteryAndDesertion-en.disabled
  test/end-to-end/paths/amend.disabled
  test/end-to-end/paths/aosDrafted.disabled
  test/end-to-end/paths/basicDivorce.disabled
  test/end-to-end/paths/exitPaths.disabled
  test/end-to-end/paths/exitScenarios.disabled
  test/end-to-end/paths/foreignMarriageCertificates.disabled
  test/end-to-end/paths/invalidCsrf.disabled
  test/end-to-end/paths/jurisdictionConnections.disabled
  test/end-to-end/paths/livingTogether.disabled
  test/end-to-end/paths/logout.disabled
  test/end-to-end/paths/payment.disabled
  test/end-to-end/paths/postcode.disabled
  test/end-to-end/paths/reasonsForDivorce.disabled
  test/end-to-end/paths/save-resume.disabled
  test/end-to-end/paths/uploadMarriageCertificate.disabled
  test/end-to-end/smoke/smoketest.js
Labels: ns:divorce, prd:div, rel:div-pfe-pr-992
