Repository hmcts/div-petitioner-frontend, pull requests merged in 2022-04, with the labels that each got.

#1005 Suppressing ajv
  yarn-audit-known-issues
Labels: ns:divorce, prd:div, rel:div-pfe-pr-1005

#1009 Dfr 979 change webchat url
  app.js
  app/steps/avaya-webchat/template.html
  app/views/includes/scripts.html
  app/views/includes/web_chat.html
  charts/div-pfe/values.demo.template.yaml
  charts/div-pfe/values.preview.template.yaml
  config/custom-environment-variables.yaml
  config/default.yaml
  yarn-audit-known-issues
Labels: ns:divorce, prd:div, rel:div-pfe-pr-1009

#1008 bumping moment
  package.json
  yarn-audit-known-issues
  yarn.lock
Labels: ns:divorce, prd:div, rel:div-pfe-pr-1008

#1012 Update Async
  package.json
  yarn.lock
Labels: ns:divorce, prd:div, rel:div-pfe-pr-1012

#1013 Updating app key
  infrastructure/main.tf
Labels: ns:divorce, prd:div, rel:div-pfe-pr-1013
